### ISSUE TITLE
les liens ne marche pas dans le navigateur

### ISSUE THREAD

**Issue by mickael88** [KasRoudra/PyPhisher#10]
the two generated links do not work on my browser I do not understand why besides I have the impression that there is a file which must be downloaded

**Comment by Winst0nCH** [comment]
Tunneling falied! ![Screenshot_20211117-233227_Termux.jpg](https://user-images.githubusercontent.com/94007870/142269919-0d306951-8935-445d-a060-bf88923cd68f.jpg)

**Comment by mickael88** [comment]
i don't know how to configure ngrok

**Comment by KasRoudra** [comment]
@Winst0nCH Turn on hotspot and try again

**Comment by KasRoudra** [comment]
@mickael88 Try this [solution](https://github.com/KasRoudra/PyPhisher/issues/1) to configure ngrok
