### ISSUE TITLE
Website's not showing 

### ISSUE THREAD

**Issue by wabbitEater** [KasRoudra/PyPhisher#101]
When I click on my generated URL it comes up with a blank white page with the words "It Works!" instead of the chosen template

**Comment by KasRoudra** [comment]
@wabbitEater It happens for which template and for which url(ngrok/cloudflared)?

**Comment by wabbitEater** [comment]
@KasRoudra it happened for steam and Instagram while using ngrok I have yet to try any other templates

**Comment by KasRoudra** [comment]
@wabbitEater Haven't you tried cloudflared url?

**Comment by wabbitEater** [comment]
@KasRoudra no i haven't i watched some tutorial using ngrok and have not looked into cloudlared

**Comment by wabbitEater** [comment]
@KasRoudra Do i need to make an account and setup cloudflared for those links to generate or should they already. Becuase when I run pyphisher its says that cloudflared failed to start but it does however generate my ngrok links.

**Comment by KasRoudra** [comment]
@wabbitEater Cloudflared is free and doesn't have any such issue. You need to troubleshoot the error by running `$HOME/.tunneler/cloudflared tunnel -url 127.0.0.1:8080`. Put screenshot here

**Comment by wabbitEater** [comment]
@KasRoudra zsh: no such file or directory: /Users/blank/.tunneler/cloudflared

**Comment by KasRoudra** [comment]
@wabbitEater For mac users, I suggest using docker image. Check here https://github.com/KasRoudra/PyPhisher#docker

**Comment by wabbitEater** [comment]
@KasRoudra I saw you give this advice to another person having a similar problem but can you be more specific on what you mean by use the docker image? I tried git clone on this new GitHub link but that came up with an error so I must be missing something or not understanding what you want me to do. And thank you by the way for all your help so far.

**Comment by wabbitEater** [comment]
@KasRoudra I looked into it a bit more and I think what you wanted me to do was run these commands:
sudo docker pull kasroudra/pyphisher
sudo docker run --rm -it kasroudra/pyphisher

however, I got this error in return:
Using default tag: latest
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?

**Comment by KasRoudra** [comment]
@wabbitEater My code is written and tested in a linux. I can't test it on mac, therefore I suggest mac user to run docker. And for your problem take a look at [here](https://stackoverflow.com/questions/44678725/cannot-connect-to-the-docker-daemon-at-unix-var-run-docker-sock-is-the-docker)

**Comment by wabbitEater** [comment]
@KasRoudra I finally got it to work! Thank you so much for all of your help.
