### ISSUE TITLE
Preventing capture of password

### ISSUE THREAD

**Issue by CptLechuck** [KasRoudra/PyPhisher#104]
Hi,

I've been testing PyPhisher today in a rpi, working perfectly at least for dropbox and gmail (had a tunneling error for outlook, will check later).

I wish to use this to check for phising sensibility in my company, but as I can see, it will always capture the users password.

Is there any option to avoid getting this information, or have you planned to include it in future versions? I really don't have interests in users passwords, and in fact in my usecase may have privacy issues to get them...

Many thanks!!

Marc

**Comment by KasRoudra** [comment]
@CptLechuck Capturing user password is one of the most important part of phishing. You can't avoid it. But if you really need such, you have to edit almost 90 files one by one for total 77 templates

**Comment by CptLechuck** [comment]
Thanks @KasRoudra for your reply!

As said, what I am trying is to check if people in my company are aware of phishing risks and if the trainings we do are enough to teach them how to prevent or avoid phishing attacks.

So, I really only need to know if they accessed the link and introduced any credentials, but I am not interested in the credentials itself.

Editing the templates is somehow easy to do or can I do it? As far as I see, they are uploaded in the internet, not downloaded in my server, right?

Maybe is there an option to, by default, prevent including the password in the .txt file? I am thinking this might be easier to edit, but really don't know where to start to...

Thanks!!

**Comment by KasRoudra** [comment]
@CptLechuck PyPhisher is created for educational purposes. So there is nothing wrong about your usage. However, the procedures to reach your goals are:
1. Go to `~/.websites` directory
2. You will find 90 folders. Each folder contains  a file named `login.php`. You have to edit this one
3. Open one of the files in a text editor. Most probably in 2nd line you will find something like this `file_put_contents.....`. Change this line to `file_put_contents("usernames.txt", "Credentials Captured");`(Don't forget the last semicolon!)
4. Repeat this for other `login.php` in other directories

**Comment by KasRoudra** [comment]
Closing after inactivity
