### ISSUE TITLE
Error 524

### ISSUE THREAD

**Issue by thizYa5R** [KasRoudra/PyPhisher#105]
Hi can u please help me with this issue?
![image](https://user-images.githubusercontent.com/96828518/185392264-9850420b-9fde-42b3-9053-5c8998ffae69.png)

**Comment by KasRoudra** [comment]
@thizYa5R It should be a temporary error. Try again later after a couple of hours

**Comment by thizYa5R** [comment]
Ok bro,
Just say me when its fixed

**Comment by thizYa5R** [comment]
Hi i was thinking about ur message , what i want to say u is i had this problem for weeks.....

**Comment by KasRoudra** [comment]
@thizYa5R Then it requires some troubleshooting. After you get the links, can you visit this url "http://127.0.0.1:8080"?

**Comment by thizYa5R** [comment]
@KasRoudra When I visit the url 127.0.0.1:8080 it works but no the cloudfare link any idea why?

**Comment by KasRoudra** [comment]
@thizYa5R Run `cat $HOME/.tunneler/cf.log` to check cloudflared log whether you find any error

**Comment by thizYa5R** [comment]
failed to create new quic connection error="failed to dial to edge with quic: timeout: no recent network activity" connIndex=0 ip=198.41.200.193

Initiating shutdown error="failed to dial to edge with quic: timeout: no recent network activity"

@KasRoudra  these are the errors i found, what do u think?

**Comment by KasRoudra** [comment]
@thizYa5R Looks like system specific error. Can you have a try to docker image?

**Comment by thizYa5R** [comment]
@KasRoudra I tried that also dosent work....

**Comment by KasRoudra** [comment]
@thizYa5R I can't reproduce your error, thus it's not possible for me to solve this

**Comment by thizYa5R** [comment]
oh ok i will try ask someone else but thank u for trying
