### ISSUE TITLE
NGROK banned account

### ISSUE THREAD

**Issue by cannotsitby** [KasRoudra/PyPhisher#106]
Everything worked fine until I clicked on the link generated. Fake website loads and then after a few seconds an error comes up in Chrome warning that this site is unsafe and cannot proceed. Closing the browser and trying to launch the link again brings up an error that the account associated with the NGROK auth token has been banned. 

I was going to try to generate a new token, but not sure if the same error will happen. Do you have a work around?

**Comment by KasRoudra** [comment]
@cannotsitby Ngrok discourages phishing entirely. You may need a pro ngrok account to allow phishing in ngrok. However, any more token from that won't work. If you are free user, you may create a new ngrok account and try to continue( but the issue may appear again)

**Comment by cannotsitby** [comment]
The code uses ngrok by default which appears to disallow this process. What other option can be used that will not block this? Besides ngrok?

**Comment by KasRoudra** [comment]
@cannotsitby You may try cloudflare links or create a free loclx account for 15 minutes loclx links
