### ISSUE TITLE
out of date

### ISSUE THREAD

**Issue by LuckyDucky3607** [KasRoudra/PyPhisher#108]
the instagram traditional login oage is out of date it is showing the iphone 7 instead of the iphone x or whatever (its showing a ine with a home button while the current original one doesnt have one) can you tell me how to fix this manually or even better update the script to make it up to date??

**Comment by KasRoudra** [comment]
@LuckyDucky3607 A current fix could be editing 13304th and 13317th lines of `~/.websites/instagram/login.html.php`. Change the image link to your desired one

**Comment by KasRoudra** [comment]
Fix and update will refer to #100
