### ISSUE TITLE
Tunnel error

### ISSUE THREAD

**Issue by halazkaz** [KasRoudra/PyPhisher#109]
Screenshot : 
![Screenshot_20220823-013715_Termux](https://user-images.githubusercontent.com/93034146/186038304-2c6df2f9-5f6c-4a3e-a39a-da58f9ebafbe.jpg)

**Comment by KasRoudra** [comment]
@halazkaz https://github.com/KasRoudra/PyPhisher#solution-of-common-issues

**Comment by halazkaz** [comment]
Ok thanks
