### ISSUE TITLE
Ngrok tunneling and Cloudfared

### ISSUE THREAD

**Issue by zedarchy** [KasRoudra/PyPhisher#11]
Hi, it's me again... Soo i made same question on zphisher by htr-tech and used this as the alternative for zphisher, and i know the source code is from zphisher for pyphisher... It shows a tunneling failed on termux and Kali distro
Even with hotspot on it doesn't work
**@KasRoudra please fix this**

**Comment by KasRoudra** [comment]
@zedarchy 
There is no error in pyphisher and even zphisher. They are working fine. Possibly, there are some issue in your device. You may try [Replit](https://replit.com) to run those. However, for you device, run some commands and let me know outputs:
`uname -m`
`cd $HOME/.ngrokfolder && ./ngrok http 8080`
`cd $HOME/.cffolder && ./cloudflared tunnel -url 127.0.0.1:8080`
