### ISSUE TITLE
The instrgram link doesn't capture login credentials when logged.  Am I doing something wrong?

### ISSUE THREAD

**Issue by Anog34** [KasRoudra/PyPhisher#110]

**Comment by KasRoudra** [comment]
@Anog34 Which link? Ngrok or cloudflare or loclx?
Which instagram? With otp or without otp?
I need those info to check

**Comment by Anog34** [comment]
http - Cloudflare - without otp I'm pretty sure...

Thanks for your prompt response dude!

**Comment by KasRoudra** [comment]
@Anog34 I've just checked no otp instagram with cloudflared but failed to reproduce your issue. Capture was successful. Can you test some other templates?

**Comment by Anog34** [comment]
Sure will do

**Comment by KasRoudra** [comment]
@Anog34 Any update?

**Comment by Anog34** [comment]
Yes it still actually didn't work with another template. The instagram
included which is really the template I need. I don't rule it being
something on my end however.

**Comment by Anog34** [comment]
It's probably worth noting also that when I test the link/template myself;
if I go to enter my credentials/log in details after entering both I'm not
actually able to click the login button because the option never becomes
available if that makes sense? As it normally would when you go do this...

Hopefully that provides some useful info to.

Thanks,

**Comment by KasRoudra** [comment]
@Anog34 I assume it is caused by the browser. How many browsers have you tried?

**Comment by Anog34** [comment]
Hi mate do you have telegram or whatsapp?

**Comment by KasRoudra** [comment]
@Anog34 Not yet. Only mail, messenger, github
