### ISSUE TITLE
-t tunnel option not working

### ISSUE THREAD

**Issue by cannotsitby** [KasRoudra/PyPhisher#111]
running the -t loclx option does not seem to be working, it still defaults to ngrok. not sure if i'm missing something?

also when the link is generated, how do you suggest getting this link to users because it looks suspicious as generated. could the html from the login page be sent in an email?

**Comment by KasRoudra** [comment]
@cannotsitby Does the loclx link generate yet?
I don't get your last query. Can you explain more?

**Comment by cannotsitby** [comment]
running -t loclx to use loclx does not work, it generates a ngrok link

**Comment by KasRoudra** [comment]
@cannotsitby -t is for url shortener. By default PyPhisher tries to generate all links. If you want to use loclx, you need to use loclx token

**Comment by cannotsitby** [comment]
yes i have the loclx token but how do i get your code to use loclx instead of ngrok?

**Comment by KasRoudra** [comment]
@cannotsitby Run `$HOME/.tunneler/loclx tunnel http -t :8080` and let me know the output

**Comment by fzazdbl** [comment]
Sa fonctionne pas
