### ISSUE TITLE
Update tool and templates PyPhisher.

### ISSUE THREAD

**Issue by Darkrevengehack** [KasRoudra/PyPhisher#112]
Hello friend, it would be good if you update the PyPhisher tool for a better use, do not remove it from gtjub or anything similar pls, it is the best tool for phishing that I have tried bro, I hope you can update the templates of this tool, to others I have shared your PyPhisher tool thousands of times bro, I know you can, go ahead friend.

**Comment by KasRoudra** [comment]
@Darkrevengehack You should be more specific on what update is required on tool and which template should be updated

**Comment by hhajj** [comment]
Hello
why do the generated url's request a confirmation when opened ?
![Capture](https://user-images.githubusercontent.com/39116287/186953205-7c4f282b-b5ae-49ec-9130-a98e2b942d8d.PNG)

**Comment by KasRoudra** [comment]
@hhajj This will always happen with links containing "@". Use main links which don't include "@"

**Comment by Darkrevengehack** [comment]
> @hhajjEsto siempre sucederá con enlaces que contengan "@". Use enlaces principales que no incluyan "@"

that can't be fixed?

**Comment by Darkrevengehack** [comment]
> @DarkrevengehackDebe ser más específico sobre qué actualización se requiere en la herramienta y qué plantilla debe actualizarse

You have to update the [05] Instagram Traditional template, and you have to fix cloudflared link detection in Google, ngrok doesn't work for phishing lately, it's more for tcp/udp connections.

**Comment by fzazdbl** [comment]
yes here I was thinking why the tunel did not fly to connect for the physher ducoup do you have a solution because I tried to change to go from nrok to lolcx but its not working who can help me and thank you I understood serious to your comment

**Comment by Darkrevengehack** [comment]
> sí, aquí estaba pensando por qué el túnel no voló para conectarse para el physher ducoup, ¿tienes una solución porque traté de cambiar para pasar de nrok a lolcx pero no funciona, quién puede ayudarme y gracias, entendí en serio tu comentario?

Let's ask KasRoundra to update the tool to make it work properly.

**Comment by KasRoudra** [comment]
@Darkrevengehack Can you elaborate on "cloudflared detection on google"? I can't reproduce it

**Comment by KasRoudra** [comment]
@fzazdbl If your token is correct then you will get loclx links. You may troubleshoot using `$HOME/.tunneler/loclx tunnel --raw-mode http :8080`

**Comment by fzazdbl** [comment]
@KasRoudra thank you for your answer I just want to know how to check our token is good please?

**Comment by fzazdbl** [comment]
> @fzazdbl If your token is correct then you will get loclx links. You may troubleshoot using `$HOME/.tunneler/loclx tunnel --raw-mode http :8080

Sorry but it didn't work for me because when I put the command it says "Error: cant call localXpose" I don't know what the problem is and I'm on termux if it can simplify the thing `

**Comment by KasRoudra** [comment]
@fzazdbl Maybe you need to turn on hotspot. Then run this `$HOME/.tunneler/loclx account status`

**Comment by fzazdbl** [comment]
it makes me you must login

**Comment by KasRoudra** [comment]
@fzazdbl Generate a token from https://localxpose.io. Then run `$HOME/.tunneler/loclx account login`. Paste your token, press enter

**Comment by fzazdbl** [comment]
Wait, I'm going to reset the application and I'm going to reinstall pyphiser from the start.

**Comment by fzazdbl** [comment]
> @fzazdbl Generate a token from https://localxpose.io. Then run `$HOME/.tunneler/loclx account login`. Paste your token, press enter

Okay

**Comment by fzazdbl** [comment]
@KasRoudra I just did everything vree an account on lolcx copy the token and I went to termux type the command you told me suddenly they told me to put the token I put it it says "Error: cant call localXpose" I am sorry for this inconvenience

**Comment by KasRoudra** [comment]
@fzazdbl Why did you run that without hotsppt?

**Comment by Darkrevengehack** [comment]
> @Darkrevengehack¿Puede dar más detalles sobre la "detección de nubes en Google"? no puedo reproducirlo

Of course, the problem is when I send the link, after a few minutes, it becomes discoverable in Google, even the cloudflared server becomes discoverable by Google, and also when it camouflaged the link with maskphish or with the camouflaged one that PyPhisher brings.

The loclx server does not appear within PyPhisher either, not only to me, but to others I know as well, I want to distribute this tool to give you the credits and that they give you a star To you, I hope you can fix those errors by maintaining this phishing tool.

**Comment by KasRoudra** [comment]
@Darkrevengehack How does google get your link? May be it was detected by cloudflare itself. And for loclx, are you using loclx token? With token everything runs fine

**Comment by Darkrevengehack** [comment]
> @Darkrevengehack¿Cómo obtiene Google tu enlace? Puede ser que haya sido detectado por el propio cloudflare. Y para loclx, ¿estás usando el token loclx? Con token todo funciona bien

google no, the problem is cloudflare, do something to prevent that from happening.

**Comment by Darkrevengehack** [comment]
> @Darkrevengehack¿Cómo obtiene Google tu enlace? Puede ser que haya sido detectado por el propio cloudflare. Y para loclx, ¿estás usando el token loclx? Con token todo funciona bien

Loclx the PyPhisher tool does not ask for the loclx server token, maybe if you update that there will be no question about configuring your tool inside some terminal with the loclx token.

**Comment by KasRoudra** [comment]
@Darkrevengehack I've figured out the issue in loclx. They recent update has some breaking changes. However, I can't reproduce cloudflare issue. When your link gets detected do you see any external ip (that doesn't belong to you) printed in pyphisher? If so, paste the ip here

**Comment by Darkrevengehack** [comment]
> @DarkrevengehackHe descubierto el problema en loclx. La actualización reciente tiene algunos cambios importantes. Sin embargo, no puedo reproducir el problema de Cloudflare. Cuando se detecta su enlace, ¿ve alguna IP externa (que no le pertenece) impresa en pyphisher? Si es así pega aquí la ip

with external ip do you mean the ip that appears to the ip of the link generated by cloudflare in pyphisher?

**Comment by KasRoudra** [comment]
@Darkrevengehack The ip which is shown by PyPhisher but isn't your ip nor victim ip

**Comment by Darkrevengehack** [comment]
> @DarkrevengehackLa ip que muestra PyPhisher pero no es tu ip ni la ip de la víctima

How do I know what IP is showing pyphisher?

**Comment by KasRoudra** [comment]
@Darkrevengehack When you open a link, or google tries to validate, an ip is captured and shown in terminal

**Comment by Darkrevengehack** [comment]
> @DarkrevengehackCuando abre un enlace, o Google intenta validarlo, se captura una IP y se muestra en la terminal

Mis ip son privadas xd

**Comment by KasRoudra** [comment]
@Darkrevengehack Mail me the "ip.txt" in PyPhisher folder. I hope I can find out some clue there

**Comment by Darkrevengehack** [comment]
> @Darkrevengehack Mail me the "ip.txt" in PyPhisher folder. I hope I can find out some clue there

[ip.txt](https://github.com/KasRoudra/PyPhisher/files/9448726/ip.txt)

**Comment by KasRoudra** [comment]
@Darkrevengehack Does the first ip `149.154.161.205` belong to you?

**Comment by Darkrevengehack** [comment]
> @Darkrevengehack¿La primera ip `149.154.161.205`te pertenece?

No, es una ip de prueba con concentimiento.

**Comment by KasRoudra** [comment]
@Darkrevengehack Checkout version 2.0. Loclx is fixed and new link should be available
