### ISSUE TITLE
pip3 not found

### ISSUE THREAD

**Issue by Kitopvibe1** [KasRoudra/PyPhisher#114]
python3 pyphisher.py
Installing bs4
/data/data/com.termux/files/usr/bin/sh: 1: pip3: not found
bs4 cannot be installed! Install it manually by 'pip3 install bs4

**Comment by KasRoudra** [comment]
@Kitopvibe1 Run `apt remove python && apt update && pkg install python` Then run pyphisher again

**Comment by Kitopvibe1** [comment]
Thanks but I got another problem now

websites.zip  [===============>          ] 61.64%
[!] Download failed due to: HTTPSConnectionPool(host='objects.githubusercontent.com', port=443): Read timed out.
![Uploading Screenshot_20220831-150745.jpg…]()

**Comment by KasRoudra** [comment]
@Kitopvibe1 That is caused due to slow internet speed, just retry when you've a good bandwidth

**Comment by Kitopvibe1** [comment]
And this also
"File is not a zip file"
![Uploading Screenshot_20220831-151548.jpg…]()

**Comment by KasRoudra** [comment]
@Kitopvibe1 Same cause. Half downloaded file cann't be unzipped. A re-run of pyphisher will start downloading again and if internet is good, everything will go fine

**Comment by Scarletalvey** [comment]
What about linux
