### ISSUE TITLE
cloudflared server not working

### ISSUE THREAD

**Issue by Darkrevengehack** [KasRoudra/PyPhisher#117]
friend kasroundra, cloudflared stopped working for phishing, I need an explanation, why it stopped working!!!

It's like disabled, when I start with the command: cloudflared -url localhost:8080 I get the following warning: failed to request quick Tunnel: Post "https://api.trycloudflare.com/tunnel": dial tcp 127.9.9.9:443: connect: connection refused

**Comment by KasRoudra** [comment]
@Darkrevengehack Irreproducible issue. In my devices it is working fine. What about your friends; do they face same issue? You may open an issue in official cloudflared repository if you want
