### ISSUE TITLE
Press enter three times for ssh key generation

### ISSUE THREAD

**Issue by Comrad30** [KasRoudra/PyPhisher#118]
And Where Is the Custom url Maker? 

How to solved this problem ![Screenshot_2022-09-04-22-01-26-24.jpg](https://user-images.githubusercontent.com/95214573/188322652-f261291b-e2e3-4fdf-ab3d-1feebfdc1600.jpg)

**Comment by KasRoudra** [comment]
@Comrad30 This isn't a problem. press enter three times

**Comment by Comrad30** [comment]
And Bro Where is The CUSTOM Url maker?

**Comment by KasRoudra** [comment]
@Comrad30 That is still available.
