### ISSUE TITLE
getting directory does not exist error

### ISSUE THREAD

**Issue by jdawg443** [KasRoudra/PyPhisher#120]
getting this error after listing a directory for a custom site.

![image](https://user-images.githubusercontent.com/112841428/188356872-77a71ead-2e54-4f17-bd5d-b8cd194735b0.png)

i cant figure out why it isnt working :( any help?

**Comment by KasRoudra** [comment]
@jdawg443 Your input a file path, not a directory path. Unzip that to a folder and then use full folder path
