### ISSUE TITLE
Problem with the camouflage of a link for phishing

### ISSUE THREAD

**Issue by Darkrevengehack** [KasRoudra/PyPhisher#121]
KasRoundra please update your tool now as I am distributing it but everyone including me is facing the following problem:

![Screenshot_20220905-215352](https://user-images.githubusercontent.com/103399387/188525514-1e6ba500-468f-4240-afdd-f283f6594158.png)
![Screenshot_20220905-215431](https://user-images.githubusercontent.com/103399387/188525530-2c01b2df-d02e-4232-a4b1-55c994d9f139.png)

En la primera imagen, se queda pegado el "google.com" y hay que ponerlo de nuevo para que se ejecute, en la segunda imagen pasa lo mismo que en la primera imagen.

**Comment by KasRoudra** [comment]
@Darkrevengehack Tunneler `localhostrun` is affecting user input resulting into such issue. If you need a immediate fix you can delete 863th line in pyphisher. This will stop localhostrun and url-shortener will wok just fine

**Comment by KasRoudra** [comment]
@Darkrevengehack Update pyphisher. I hope the last update will solve the issue
