### ISSUE TITLE
I feel embarrassed

### ISSUE THREAD

**Issue by p-i-c-o** [KasRoudra/PyPhisher#122]
I changed the type speed from 0.05 to 0.03, and I don't know how to go back without the script telling me
<img width="361" alt="Screen Shot 2022-09-07 at 10 23 48" src="https://user-images.githubusercontent.com/95228665/188828782-f82ce878-9535-451e-8b76-69c84c308c2f.png">

I'm sorry.

How do I fix this?

**Comment by KasRoudra** [comment]
@p-i-c-o Run `git restore pyphisher.py`
