### ISSUE TITLE
no internet issue

### ISSUE THREAD

**Issue by kevinever** [KasRoudra/PyPhisher#124]
i tried several times but it is saying that i do not have the internet yet my internet is super fast pleas help.

![image](https://user-images.githu
![Screen Shot 2022-09-12 at 4 38 29 PM](https://user-images.githubusercontent.com/15107339/189682820-bbfa2a0e-5d9c-4e49-8f32-f11125625cfa.png)
busercontent.com/15107339/189682543-00be4055-8ded-4e08-9346-8cfd31bb5e0e.png)

**Comment by KasRoudra** [comment]
@kevinever Run `python3 pyphisher.py --noupdate`

**Comment by kevinever** [comment]
@KasRoudra it did work indeed thanks fam

**Comment by Azeem-cloud** [comment]
Tunneling failed!

**Comment by KasRoudra** [comment]
@Azeem-cloud Attach a screenshot

**Comment by Azeem-cloud** [comment]
![Uploading IMG_20221214_152739_126.jpg…]()
