### ISSUE TITLE
Cloudflared not working, fix immediately

### ISSUE THREAD

**Issue by Darkrevengehack** [KasRoudra/PyPhisher#128]
Hello friend, cloudflared does not work, because when 2 or 3 people open the link, it is blocked, warning of phishing and/or data extraction, this needs an immediate solution.

![IMG-20220914-WA0036](https://user-images.githubusercontent.com/103399387/190276866-77d10b52-ab0c-4073-ab2f-89a2ed68feff.jpg)

**Comment by KasRoudra** [comment]
@Darkrevengehack This can't be fixed. It's a normal behaviour of secured browsers against cloudflared
