### ISSUE TITLE
Doesn't show CSS for Facebook links 

### ISSUE THREAD

**Issue by roskosboskos** [KasRoudra/PyPhisher#13]
Doesn't show CSS for Facebook links (not sure if others links have the same problem)

**Comment by KasRoudra** [comment]
@roskosboskos The css files used by facebook-html has been deleted from facebook's cdn server. Other website templates are working fine. Try those.

**Comment by kanishkthamman** [comment]
> Doesn't show CSS for Facebook links (not sure if others links have the same problem)

done it is fixed now you can try

**Comment by KasRoudra** [comment]
@kanishkthamman where? You've closed the pull request!

**Comment by KasRoudra** [comment]
[Soloved](https://github.com/KasRoudra/PyPhisher/pull/15)
Thanks to @kanishkthamman
