### ISSUE TITLE
Suspected Phishing Site message pops up....

### ISSUE THREAD

**Issue by Zehir568** [KasRoudra/PyPhisher#130]
At first this problem did not occur, but now it occurs almost every time, does anyone know the solution to this problem?

__
![Screenshot_20220916-165130_Chrome](https://user-images.githubusercontent.com/113722848/190721984-910824db-2ca1-48a3-aa48-6bc19fbad8ab.jpg)
![Screenshot_20220915-230341_Chrome](https://user-images.githubusercontent.com/113722848/190721999-e15f884a-e5e2-47fd-86a5-531201c6bd55.jpg)
---
And always when I choose the cloudflared URL, can anyone help?

**Comment by KasRoudra** [comment]
@Zehir568 First one can't be solved. For second one, mail me the ip.txt

**Comment by Zehir568** [comment]
> 

I sent u an email

**Comment by KasRoudra** [comment]
@Zehir568 Run `rm -rf ~/.websites` and then start pyphisher. Let me know if the second error persists
