### ISSUE TITLE
tool not running

### ISSUE THREAD

**Issue by ghost** [KasRoudra/PyPhisher#132]
when i run the tool its showing up as wget:unable to resolve host address raw.githubusercontent.com and tool isnt running plzz help

**Comment by KasRoudra** [comment]
@Adamsmithy Upload a screenshot

**Comment by Adamsmithy** [comment]
[](url)

> Owner

![20220918_130835](https://user-images.githubusercontent.com/113823577/190891875-056098f6-7ff6-4933-9b28-72f9721cb638.jpg)

**Comment by KasRoudra** [comment]
@Adamsmithy This an issue of your machine or wget itself. Try updating wget or use docker
