### ISSUE TITLE
File is not Zip File

### ISSUE THREAD

**Issue by mohajiomar** [KasRoudra/PyPhisher#133]
When it dowloaded the website.zip it actually says file is not zip file.
![16635407590985012941875012654552](https://user-images.githubusercontent.com/84285205/190931072-b2b092ee-ca62-4af7-8ae0-ccef2bd89878.jpg)

**Comment by KasRoudra** [comment]
@mohajiomar This means download was interrupted by slow internet resulting into corrupted zip file. Just run pyphisher again

**Comment by mohajiomar** [comment]
> 

Thank you it worked I runned it again and the problem solved
