### ISSUE TITLE
Instants Blocked link Facebook 

### ISSUE THREAD

**Issue by Comrad30** [KasRoudra/PyPhisher#134]
I cannot share it Facebook instant Block link.

**Comment by KasRoudra** [comment]
@Comrad30 Cloudflared links are always allowed

**Comment by Comrad30** [comment]
How to installed cloudfare in PyPhisher?

**Comment by KasRoudra** [comment]
@Comrad30 Run `$HOME/.tunneler/cloudflared tunnel -url 127.0.0.1:8080` and send screenshot

**Comment by Comrad30** [comment]
![Screenshot_2022-09-20-23-28-04-96.jpg](https://user-images.githubusercontent.com/95214573/191324897-3f8ef6d6-c4b2-4d56-85a4-4df2d4a9d994.jpg)

**Comment by Comrad30** [comment]
![Screenshot_2022-09-20-23-30-50-56.jpg](https://user-images.githubusercontent.com/95214573/191325452-ff0c2b69-3cba-4544-bb0a-dd534a011806.jpg)

**Comment by Comrad30** [comment]
![Screenshot_2022-09-20-23-36-13-17.jpg](https://user-images.githubusercontent.com/95214573/191326393-19650f85-f6fb-4a19-8340-0dee35aff37d.jpg)

**Comment by KasRoudra** [comment]
@Comrad30 There are a lot of errors. Maybe it's a temporary problem or a problem of your device
