### ISSUE TITLE
ngrok authtoken error

### ISSUE THREAD

**Issue by thechiragjogani** [KasRoudra/PyPhisher#138]
ngrok config add-authtoken {token} is deprecated
ngrok authtoken {token} is working

please fix it.

Most awesome phishing tool I ever used. Keep up the good work.

**Comment by thechiragjogani** [comment]
Bro documentation is also deprecated.

**Comment by thechiragjogani** [comment]
@KasRoudra 
<img width="626" alt="image" src="https://user-images.githubusercontent.com/52485622/192245915-0a256522-0f40-4202-809b-061d28a3f16a.png">

**Comment by thechiragjogani** [comment]
ngrok authtoken {token} 

this worked outside your tool, I tried to change the source code, then it showed message

you don't become developer by changing logo

**Comment by KasRoudra** [comment]
@thechiragjogani Your ngrok is outdated for more than one year. Your version is 2.3 whereas latest one is 3.1 My code uses ngrok v3 and thus it supports latest documentation. Everything is ok

**Comment by thechiragjogani** [comment]
i used my ngrok after the automatic ngrok setup from your tool didn't took my authtoken at prompt and didn't run, please find the error here then

**Comment by KasRoudra** [comment]
@thechiragjogani Run `rm -rf ~/.ngrok2 ~/.config/ngrok` and then run PyPhisher again. It will ask for token

**Comment by thechiragjogani** [comment]
i think the binary of ngrok being used is not changed in your tool, the ngrok (outdated) binary is being used, just a thought can you please recheck

**Comment by thechiragjogani** [comment]
it asks for token, but shows error that config argument is not present

even the .tunnelers directory is not being created. or is it deleted after scripts execution?

**Comment by thechiragjogani** [comment]
yes this is the issue 

> i think the binary of ngrok being used is not changed in your tool, the ngrok (outdated) binary is being used, just a thought can you please recheck

**Comment by thechiragjogani** [comment]
![image](https://user-images.githubusercontent.com/52485622/192251157-464adfd1-b34d-454f-aeeb-6642b6e16d40.png)

**Comment by thechiragjogani** [comment]
i think a fix would be to delete the old ngrok binary from directories in $PATH variable, or hardcoding the location of ngrok binary present in ~/.tunneler/ngrok

**Comment by KasRoudra** [comment]
@thechiragjogani The download link of ngrok in my code refers to version 3. It's your system which has ngrok pre-installed but an old version. A possible fix could be running `rm -rf $(which ngrok)`

**Comment by thechiragjogani** [comment]
please incorporate it in the tool with a check, so others dont face the same problem

**Comment by KasRoudra** [comment]
@thechiragjogani Has your problem been solved?

**Comment by thechiragjogani** [comment]
yes

sudo rm -rf $(which ngrok)
rm -rf ~/.ngrok2 ~/.config/ngrok
