### ISSUE TITLE
Cloudflared link problem

### ISSUE THREAD

**Issue by Zehir568** [KasRoudra/PyPhisher#139]
KasRoudra,sorry for the late reply,I know that you closed the previous subject,I didn't have a chance to test what you told me,I was out of the country for work...

I did what u told me.I typed (rm -rf ~/websites),then downloaded websites again and tested it on several phones,and the problem is still there...

In the previous post I did not describe some details, there is another problem with the URL structure when I create a custom link, which I will describe in another post.

Full description of the problem with (cloudflare) phishing link.

So,when I create a (cloudflared) link and send it to someone,when the victim opens that link,browser throws out the following message...

![IMG-7129834b21ad5ab33fd54c23c477a737-V](https://user-images.githubusercontent.com/113722848/193124310-8bf4a85d-8f87-4360-a975-3da0bfcaf294.jpg)

**To avoid confusion, this message is in Serbian language**.And it says that there is a misleading site in front of you,that someone can steal your data,etc...but I found the same pop-up page on the internet with the same message, which is in English.

![x](https://user-images.githubusercontent.com/113722848/193125790-44c4f1d7-2fcf-4bac-94a6-49b4e5fa6867.png)

The browser detects the link as malicious,phishing etc...

The same kind of message like this appeared when I used another script (zphisher) before.Only in a different format,but basically the same.

![x2](https://user-images.githubusercontent.com/113722848/193128383-8f19237c-e4e2-46ce-aa10-b4aefc98812b.jpg)

PyPhisher seems like a very useful script to me,and I really like it,of all the ones I know, pyphisher is the best in my opinion,it has the most possibilities. It would be good if this problem can be solved.

**Comment by KasRoudra** [comment]
@Zehir568 In your previous issue I've mentioned that first error can't be solved. That is detected by browser end. We can't prevent that. I've tried to fix the second issue which is the detection of cloudflared saying "Suspected phishing site". I hope at least that one is solved. But for further try you may email the ip.txt of some devices you've tried.

**Comment by Zehir568** [comment]
Here it is... ip.txt

pet, 30. sep 2022. 04:39 KasRoudra ***@***.***> је написао/ла:

**Comment by KasRoudra** [comment]
@Zehir568 File isn't uploaded

**Comment by Risovk** [comment]
Hello 
![Uploading Screenshot_2022-10-07-19-57-41-457_com.termux.jpg…]()

**Comment by ChillVibesMushroom** [comment]
would it be possible to run this on something like linode or aws
