### ISSUE TITLE
CloudFlare Issue

### ISSUE THREAD

**Issue by PhonMailer** [KasRoudra/PyPhisher#14]
I believe cloudflare has made changes because it wont display your url 1 and url 2. Only ngrok is displaying. Do you have any idea why?

**Comment by KasRoudra** [comment]
Often cloudflared servers go down. Maybe you were using at that time. Now I've tested PyPhisher and all 4 urls are showing. Note that if you are using from android, you need to enable hotspot. If problem remains, use `uname -m` and `cd $HOME/.cfffoder && ./cloudflared tunnel -url 127.0.0.1:8080`  to troubleshoot

**Comment by PhonMailer** [comment]
Thanks for your response and yeah I have tested and it's working now.

**Comment by PhonMailer** [comment]
Lastly bro... can you do a separation to select if one want ngrok or cloudflare?

**Comment by KasRoudra** [comment]
@PhonMailer Providing two tunnelers together is probably better than selecting
