### ISSUE TITLE
URL cannot be opened by clicking...

### ISSUE THREAD

**Issue by Zehir568** [KasRoudra/PyPhisher#140]
When I custom edit the URL,and when I send the link to the victim on viber,whatsapp,instagram,fb,or even in the sms message when I send it,the link looks like this

![x3](https://user-images.githubusercontent.com/113722848/193134164-f370ac37-d9fc-4e6e-b1b7-2bfa392720bf.jpg)

The protocol and the path of the URL are not marked,and because of this the victim cannot enter the link just by clicking.

**Comment by KasRoudra** [comment]
@Zehir568 After the recent security updates links containing @ as prefix are treated link without paths. If you want to allow path you need to skip the part before @ (inclusive).  So the link should be "https://is.gd/XXXXXX". Send it and everything will be fine
