### ISSUE TITLE
Better Discord Preview and Link

### ISSUE THREAD

**Issue by 0Zombie** [KasRoudra/PyPhisher#141]
Hey, I don't know if this is a bug. I just wanted to suggest two things. 

**1**: If you create e.g. a fake Roblox link and send it to anyone on Discord it only shows the shortened link like _https://is.gd/yHa91_, so but it would be really great if it shows the entire link on Discord like _https://www.roblox.com-users-3937837101-profile@is.gd/yPCI91_. 
(Because the shortened link looks really suspicious, but the other one looks more like a real website.)

**2**: I (think this is a bug.) If I create a link it's not showing the preview on Discord like your IP-Tracker project does. 

_**Would make me really happy if you improve or add that. :)**_

Thanks!

**Comment by KasRoudra** [comment]
@zfzd The first one might be restricted due to recent security changes. For the second issue, you may use shadow url feature. The preview of input website should be added in discord

**Comment by zfzd** [comment]
Yes that could be the reason. If you send a message with the link the grabber tool tells you that an automated process just opened the link. I think that's also a special security mode from Discord.

I alread did that and I'm using the shadow url feature. With your other project (IP-Tracker) is this feature still working. But only on Discord is this one not working. On other platforms the preview works fine. Only on Discord with this project not.

**Thanks for your time!**

**Comment by zfzd** [comment]
Hey, Sir, it's me again.

Because of issue 2, can you review the code sometime and recode some?


_**Thank you!**_

**Comment by KasRoudra** [comment]
@0Zombie IP-Tracker doesn't have any real webpage. It just redirects. So discord bot always receives the redirected url and generate preview. But PyPhisher works with real webpage. If it was a issue it won't work anywhere not whatsapp nor telegram. As it is specific to discord then we can conclude that it's an issue (probably security feature to others) of discord itself.
