### ISSUE TITLE
I wouldn't feel comfortable using your project with such "copyright" failsafe-mechanism

### ISSUE THREAD

**Issue by cwaazywabbit** [KasRoudra/PyPhisher#142]
https://github.com/KasRoudra/PyPhisher/blob/292f721bad0723f59307a578eff02e8353beec88/pyphisher.py#L92

On that line you have inserted a zlib'ed multi base32 encoded chunk as a failsafe mechanism to protect your copyright. IMHO this is bad. I would personally not use your project without having to confirm that nothing malicious have been placed there. Keeping track of changes and doing that everytime would be boring at the very least.

I suggest you remove it and focus on improvements instead, because nothing is crack-proof.

Thanks for such a great project, btw.

P.S: what you have placed there is destructive. Have mercy on those skript-kiddies.

**Comment by KasRoudra** [comment]
@cwaazywabbit My code was 100% open source in previous days. But after some days a lot of copying begin to start. Many people just copy-pastes my code and just replaces my name with their. My purpose of this line is saving my code from a guy who doesn't know programming but knows `find and replace`. If you don't edit my code, it will remain always safe for you!

**Comment by MrExpose** [comment]
Bro have you created a tool for GPS tracking?

**Comment by KasRoudra** [comment]
@MrExpose Try location option of [MaxPhisher](https://github.com/KasRoudra/MaxPhisher)

**Comment by MrExpose** [comment]
Thank you, I have tried it, i have chosen weather, entered to the link and allowed to use my location, but in the information i couldn't find geolocation of the victim

**Comment by KasRoudra** [comment]
@MrExpose Didn't you get latitude and longitude?

**Comment by KasRoudra** [comment]
@MrExpose That's all you can get from MaxPhisher. I don't have any other tool for this purpose

**Comment by MrExpose** [comment]
Bro, could you please me best tools for DDOS attacks and defacement of the website

**Comment by KasRoudra** [comment]
@MrExpose irrelevant and I don't know about any
