### ISSUE TITLE
What is URL Shadowing?

### ISSUE THREAD

**Issue by ErSeraph** [KasRoudra/PyPhisher#144]
Try to learn something, what is url shadowing? How does it work? An example please?

Thanks

**Comment by KasRoudra** [comment]
@ErSeraph This is already mentioned in PyPhisher. URL shadowing is used to generate a different preview than original one. You can add preview of google in your facebook phishing page. By this you can make you phishing site more realistic

**Comment by ErSeraph** [comment]
Ah okok I understand what you mean, so what am I doing wrong? Every time he says "URL isn't correct!"

EDIT:
Ok I figured out, the URL need to have a real preview, not all URLs work

Thanks KasRoundra!!!
