### ISSUE TITLE
plz help me 

### ISSUE THREAD

**Issue by calilope** [KasRoudra/PyPhisher#145]
(kali㉿kali)-[~]
└─$ cd PyPhisher
                                                                                                                                                                      
┌──(kali㉿kali)-[~/PyPhisher]
└─$ python3 pyphisher.py --noupdate

[+] Please wait!

[+] Downloading Ngrok...

                                                                                                                                                                      
┌──(kali㉿kali)-[~/PyPhisher]
└─$ python3 pyphisher.py           

[+] Please wait!
[!] No internet!

[!] No internet!

[!] No internet!
plz help i have nbo vpn connected and my network is stabble

**Comment by KasRoudra** [comment]
@calilope Run `python3 pyphisher.py --noupdate` again

**Comment by calilope** [comment]
k lemme try again

**Comment by calilope** [comment]
(kali㉿kali)-[~]
└─$ cd PyPhisher
                                                                                                                                                                      
┌──(kali㉿kali)-[~/PyPhisher]
└─$ python3 pyphisher.py --noupdate

[+] Please wait!

[+] Downloading Ngrok...
for how much ime do i have to wait

**Comment by KasRoudra** [comment]
@calilope Depends on your internet speed. It may take up to 5 minutes

**Comment by calilope** [comment]
nah it is showing me to enter command

**Comment by calilope** [comment]
(kali㉿kali)-[~]
└─$ cd PyPhisher
                                                                                                                                                                      
┌──(kali㉿kali)-[~/PyPhisher]
└─$ python3 pyphisher.py --noupdate

[+] Please wait!

[+] Downloading Ngrok...


                                                                                                                                                                      
┌──(kali㉿kali)-[~/PyPhisher]
└─$ python3 pyphisher.py           

[+] Please wait!
[!] No internet!

[!] No internet!

**Comment by KasRoudra** [comment]
@calilope Run in docker

**Comment by calilope** [comment]
how

**Comment by KasRoudra** [comment]
@calilope https://github.com/KasRoudra/PyPhisher#docker

**Comment by calilope** [comment]
ok i m gonna try @KasRoudra 
anyawys i m your neighbor from pakistan
and i really apreciate you for working this hard

**Comment by calilope** [comment]
thnkx

**Comment by calilope** [comment]
one last thing what is the command to open CAMHACKER
after cd cam hacker

**Comment by KasRoudra** [comment]
@calilope `./ch.sh`
