### ISSUE TITLE
Issues with PyPhiser credential mailing 

### ISSUE THREAD

**Issue by mattcrypted** [KasRoudra/PyPhisher#146]
I love this piece of fine work you did here champ. I’m trying it out and noticed the credentials don’t get mailed to the email after editing email.json 
![0DEE8B65-A603-407A-A819-8D484B70FE42](https://user-images.githubusercontent.com/106237789/195337356-0782030f-36d1-493f-81e7-72200497e96c.jpeg)

**Comment by KasRoudra** [comment]
@mattcrypted Have you chosen mail and name custom when creating that app password?
