### ISSUE TITLE
Ngrok account banned

### ISSUE THREAD

**Issue by schwungvoll** [KasRoudra/PyPhisher#148]
**Hey, does anyone have an idea how I can fix this? Because I don't wanna send my victim a link like this:**
_https://no-scam.free-robux-downloader.exe-com-pubg@is.gd/hdnaJ10_

**I think it is a cloudflare/ngrok error. I'm not really in in such things, so please give me some advice.**
![image](https://user-images.githubusercontent.com/96620548/195658904-3e63dde0-5459-451b-8071-9029c6dc46b9.png)
![image](https://user-images.githubusercontent.com/96620548/195659042-b5fa374e-d0a2-45c4-bb16-167693fce602.png)

**Comment by KasRoudra** [comment]
@0Zombie Your ngrok account is banned. Create a new account and apply that token. Cloudflare server was busy, thus the link didn't generate

**Comment by 0Zombie** [comment]
thanks dude, I thought they banned it but I didn't knew why because it seemed weird to me to jsut ban an acc

so wtf
why tf did they ban my acc lmao??

and I have another question? was that a real mod who banned me manually or jsut a thing like an auto-ban?

**Comment by KasRoudra** [comment]
@0Zombie That's simple. You are banned because you tried to do phishing which is discouraged by them. And I think you are banned by some human, not auto-detection. If it was auto detection you'd have been banned earlier
