### ISSUE TITLE
pip3 not found

### ISSUE THREAD

**Issue by Scarletalvey** [KasRoudra/PyPhisher#150]
python3 pyphisher.py
Installing requests
/bin/sh: 1: pip3: not found
Installing bs4
/bin/sh: 1: pip3: not found
requests cannot be installed! Install it manually by 'pip3 install requests'...
i cant use this and i'm getting this error please help...

**Comment by KasRoudra** [comment]
@Scarletalvey What is your distro?

**Comment by Scarletalvey** [comment]
kali linux

**Comment by Scarletalvey** [comment]
see where is giving issues ..

┌──(badboyx㉿DESKTOP-USMPNJ2)-[~/PyPhisher]
└─$ pip3 install -r files/requirements.txt
-bash: pip3: command not found

┌──(badboyx㉿DESKTOP-USMPNJ2)-[~/PyPhisher]
└─$ python3 pyphisher.py
Installing requests
/bin/sh: 1: pip3: not found
Installing bs4
/bin/sh: 1: pip3: not found
requests cannot be installed! Install it manually by 'pip3 install requests'
![image](https://user-images.githubusercontent.com/115846217/195978793-569191a2-6c6e-47f7-a1c7-946c6fce285b.png)

**Comment by KasRoudra** [comment]
@Scarletalvey Run `apt install python3-pip`
