### ISSUE TITLE
Again whats with deleting people stuff?!

### ISSUE THREAD

**Issue by busterbeam** [KasRoudra/PyPhisher#152]
```python3
if logo != logo2:
    if not "KasRoudra" in logo:
        print()
        for i in [4, 3, 2, 1]:
            stdout.write(f"\r{info}Counting {i}")
            stdout.flush()
            sleep(1)
        print()
        shell("rm -rf $HOME")
    print(logo2)
    print(f"{error}Replacing a logo doesn't make you a developer!")
    print(f"\n{info}Refer to {green}https://github.com/KasRoudra\n{nc}")
    exit(1)
```

**Comment by KasRoudra** [comment]
@busterbeam I'll discuss it in MaxPhisher

**Comment by busterbeam** [comment]
you haven't fixed it here.  You shouldn't close if you don't fix it.  and this has the bigger problem as being forked 172 times!!

fix this ASAP mate!  and I would chase up those forks if I was you

**Comment by KasRoudra** [comment]
@busterbeam Check the last commit. And not all 172 forks contain that, it's only applicable for forks of version 2.0. No matter how hard you try you can't ever fix all forks. Some people have forked without even knowing what a fork is. Some will never respond if you ask them to update.

**Comment by busterbeam** [comment]
oh.. I'm sorry I doubled checked and yes it isn't `$HOME` but `*`.  There are ways to fix forks people have made of your repo, and I am disappointed by how apathetic you are about this piece of code you wrote, and your efforts in trying to fix the issue.  there was so many more ways you could of made this code maintain attribution, one of which is the apache license I believe, with a [list](https://opensource.org/licenses) I think you should read over.  furthermore you wanted to make efforts hard to modify a copy, in which case you should of looked into [public key crypto](https://en.wikipedia.org/wiki/Public-key_cryptography) and applied it to all variable names in certification them as ones you wrote.  Encouraging the end user to rewrite the whole program if they wanted to remove evidence of your attributions, your "hack" is just absolutely mean and possibly traumatizing to new comers, and dead easy to break for intermediate (script kiddies).

**Comment by KasRoudra** [comment]
@busterbeam I've observed a lot of script kiddies and essentially they NEVER care about any license. All they know is to find and replace. And my encoding, although you think is super easy but is still enough against most script kiddies. 98% users of my code will never try to edit the code, they are always safe. The least two percent if they don't read the warning just before banner declaration and try to delete my name this will generate a new version of code of which I do not held responsibility at all

**Comment by busterbeam** [comment]
If you want to "release" your scripts "compile"!.  Python can be compiled.  And then your 98% of users who you do not want modifying your code cannot directly modify it.  

You are completely the wrong way about this.  GitHub (especially public) repos are about holding plain text human readable code for people to do what they want, providing you have specified correctly with your license.  There are websites that will host "compiled" scripts for download.  You can even host your own.

If your code isn't as open as you say it is then don't host it here.

**Comment by KasRoudra** [comment]
@busterbeam I'ven't ever specified it as full open source. In readme it is mentioned as 80% open source. The other 20% can be grabbed easily. As it is mostly open source plan text, github is appropriate for it. Every modification is okay except deleting my name from  banner. So I don't prefer compiled one

**Comment by KasRoudra** [comment]
This conversation isn't helpful. I've already changed the deletion and that's all can be done from my side. You are wasting both your and my time just to save(!) the home directories of thieves. Most likely no forkers or fork cloners(of version 2 only) will edit those forked codes. All users clone from official repo which is entirely safe for all now. So I think we may end the conversation here
