### ISSUE TITLE
Not able to download localxpose

### ISSUE THREAD

**Issue by Dstar001** [KasRoudra/PyPhisher#154]
[+] Downloading Loclx...

[!] Download failed due to: HTTPSConnectionPool(host='lxpdownloads.sgp1.digitaloceanspaces.com', port=443): Max retries exceeded with url: /downloads/loclx-linux-arm.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xe8849d18>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by KasRoudra** [comment]
@Dstar001 Re-run PyPhisher. If internet is stable, the download will start again
