### ISSUE TITLE
Localxpose authentication 

### ISSUE THREAD

**Issue by Vasanth1729** [KasRoudra/PyPhisher#155]
Authentication token was not creating and is showing login failed from the phisher

**Comment by KasRoudra** [comment]
@Vasanth1729 Provide a screenshot

**Comment by Vasanth1729** [comment]
![Screenshot_2022-10-29-13-41-16-40_84d3000e3f4017145260f7618db1d683.jpg](https://user-images.githubusercontent.com/107407573/198821188-978d823c-5d5d-470a-8284-84c24117421e.jpg)

**Comment by KasRoudra** [comment]
@Vasanth1729 Run `cat -n $(which pyphisher) | grep 554 | sed s/554//` and give screenshot

**Comment by Vasanth1729** [comment]
Hello can you modify it in victim opening link he has showing like site is blocked and showing phishing

**Comment by KasRoudra** [comment]
@Vasanth1729 For free account, this is not possible. Either use other links or buy a subscription in loclx
