### ISSUE TITLE
Error Directory not empty

### ISSUE THREAD

**Issue by Mikeyxken2** [KasRoudra/PyPhisher#157]
![4749EFB2-BECA-4789-B8D1-C7E2E72767E5](https://user-images.githubusercontent.com/117107477/199064342-6fd4a85f-1bcb-4862-b976-4feda265aad5.jpeg)

can somebody help? I dont know whats the problem is. Thanks

**Comment by KasRoudra** [comment]
@Mikeyxken2 Warning: iSH support is not confirmed. Run `rm -rf ~/.websites` and start pyphisher again

**Comment by Mikeyxken2** [comment]
> rm -rf ~/.websites

ok thank you

**Comment by KasRoudra** [comment]
@Mikeyxken2 Is it solved?
