### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted at line 906

### ISSUE THREAD

**Issue by mrohan47** [KasRoudra/PyPhisher#158]
Hi,
I'm having a couple issues here upon running. I selected the instagram option and I have not been able to get a test run so far. Please assist.
<img width="562" alt="Screen Shot 2022-10-31 at 1 10 51 PM" src="https://user-images.githubusercontent.com/60519281/199067777-9b9e8273-2d99-458b-b9df-45e6449c6b9f.png">
<img width="567" alt="Screen Shot 2022-10-31 at 1 09 54 PM" src="https://user-images.githubusercontent.com/60519281/199067787-c08af3ed-e46e-4f4f-9cad-101624459e7d.png">

**Comment by KasRoudra** [comment]
@mrohan47 Mac support is at beta stage. Please run PyPhisher in docker! 
https://github.com/KasRoudra/PyPhisher#docker

**Comment by mrohan47** [comment]
thank you sir
