### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jegerloor121** [KasRoudra/PyPhisher#160]
Error 1033 how to fix this error link

**Comment by KasRoudra** [comment]
@jegerloor121 Attach a screenshot

**Comment by KasRoudra** [comment]
@jegerloor121 This is a server side error which we've no access to. You should try other links in such cases

**Comment by jegerloor121** [comment]
The version 2.0 is good no error but when i update it and thats the result.

![1](https://user-images.githubusercontent.com/99719782/199385567-c4802438-5180-4b78-9a1d-34fc9b6eb903.PNG)

**Comment by KasRoudra** [comment]
@jegerloor121 This issue didn't cause due to version update. Rather it's a server issue applicable for all scripts using cloudflare. Hence we have no access to fix it, you have to use another service

**Comment by jegerloor121** [comment]
ahh thanks bro
