### ISSUE TITLE
Help???

### ISSUE THREAD

**Issue by MoonProxY56** [KasRoudra/PyPhisher#163]
How do u do this "files/email.json" I'm sorry but I don't know how to do it

**Comment by KasRoudra** [comment]
@MoonProxY56 What do you exactly want?

**Comment by MoonProxY56** [comment]
so for the mail thing. I don't exactly know how to do files/email.json

**Comment by KasRoudra** [comment]
@MoonProxY56 You have to use a gmail in sender field. Then use app password in the password field. You can generate one after enabling 2FA. Lastly you may set any valid email as receiver. Every info will be delivered to receiver's email

**Comment by MoonProxY56** [comment]
Ok, thanks.

**Comment by MoonProxY56** [comment]
where's the mailer on it?

**Comment by MoonProxY56** [comment]
But where does it say that stuff??? And also does it go into spam?

**Comment by KasRoudra** [comment]
@MoonProxY56 It depends on senders account. If the sender account is suspected as spamming account by google, the mails will be delivered on receiver's spam

**Comment by MoonProxY56** [comment]
Ok I'm not finding any luck with this. Is there any other way to get email
passwords?

**Comment by MoonProxY56** [comment]
Bro show me a screenshot where the mailer is

**Comment by KasRoudra** [comment]
@MoonProxY56 Try this https://www.getmailbird.com/gmail-app-password/

**Comment by MoonProxY56** [comment]
Bro I've done that but where is the mailer on pyphisher

**Comment by KasRoudra** [comment]
@MoonProxY56 Put your app password in `files/email.json` and that's enough

**Comment by MoonProxY56** [comment]
But where does it say files/email.json on termux? I'm really confused

**Comment by KasRoudra** [comment]
@MoonProxY56 Run this `nano ~/PyPhisher/files/email.json` and then edit

**Comment by MoonProxY56** [comment]
and then how do I send the email?

**Comment by KasRoudra** [comment]
@MoonProxY56 Mail will be automatically sent after each data capture
