### ISSUE TITLE
Exception has occurred: ImportError

### ISSUE THREAD

**Issue by BahoiOfficial** [KasRoudra/PyPhisher#165]
it says:
"cannot import name 'mknod' from 'os' "

What should i do?

**Comment by KasRoudra** [comment]
@BahoiOfficial What is your python version?

**Comment by BahoiOfficial** [comment]
@KasRoudra 
My python version is 3.11
I think that's the latest one.

**Comment by KasRoudra** [comment]
@BahoiOfficial And your os?

**Comment by BahoiOfficial** [comment]
@KasRoudra 
My os is windows 10 pro, the latest version of it

**Comment by KasRoudra** [comment]
@BahoiOfficial Windows is not implicitly supported. Try pyphisher in docker or virtualbox

**Comment by BahoiOfficial** [comment]
@KasRoudra ok so i have to use a virtual machine otherwise i wont be able to use that thing

**Comment by BahoiOfficial** [comment]
@KasRoudra 
![Screenshot (52)](https://user-images.githubusercontent.com/118018480/201489369-3a1cfa1d-21b3-4ac4-95d7-94b89c6029d0.png)
i dont know what to do now, please help

**Comment by KasRoudra** [comment]
@BahoiOfficial Is virtualization enabled? If not, enable it from bios

**Comment by akmoe2021** [comment]
![Screenshot_2022-11-17-02-49-35-014_com termux](https://user-images.githubusercontent.com/90706310/202287109-785660fc-d7c5-4cfc-bfa2-5adf5d1ce5f8.jpg)
I don't understand this stage

**Comment by akmoe2021** [comment]
![Uploading Screenshot_2022-11-17-02-49-35-014_com.termux.jpg…]()

**Comment by KasRoudra** [comment]
@akmoe2021 If you don't have token, why you entered `y`? Next time always enter n
