### ISSUE TITLE
link detected by chrome

### ISSUE THREAD

**Issue by itsrvsingh** [KasRoudra/PyPhisher#166]
link detected by chrome and give an alert back to safely

**Comment by KasRoudra** [comment]
@itsrvsingh That's a security feature of safe browsers. We don't have any control over it. So, you have to try other links

**Comment by itsrvsingh** [comment]
I tried only the custom link

**Comment by itsrvsingh** [comment]
all links catch by chrome

**Comment by KasRoudra** [comment]
@itsrvsingh Run localhostrun links
