### ISSUE TITLE
pyphisher

### ISSUE THREAD

**Issue by livinglife33** [KasRoudra/PyPhisher#169]
i wanna use the custom (#78) on pyphisher to make a custom phishing page and it asks for what the directory is what do i do ?

**Comment by KasRoudra** [comment]
@livinglife33 Learn web development and then build phishing page. Otherwise collect phishing site from somewhere else

**Comment by livinglife33** [comment]
> @livinglife33 Learn web development and then build phishing page. Otherwise collect phishing site from somewhere else

how do i get started /

**Comment by KasRoudra** [comment]
@livinglife33 Do some courses in udemy/coursera or follow WebDev Simplified on youtube

**Comment by livinglife33** [comment]
Okay thank u
