### ISSUE TITLE
need help with new google 

### ISSUE THREAD

**Issue by oaosdpo** [KasRoudra/PyPhisher#17]
can you send a video or demonstration on how you got it to work? can you make a new replit and put the site on there without pyphisher and just the files?

**Comment by KasRoudra** [comment]
@oaosdpo Yeap. Just unzip all files to a directory, then `cd` into that directory. After that, start a php server by `php -S 127.0.0.1:8000`. Now you can open your browser and go to http://127.0.0.1:8000. You can test phishing page there. It will save ip and usernames in respective txt files

**Comment by oaosdpo** [comment]
i am using replit and there is a problem in the login.php code where if i download the google zip you sent me it downloads login.php instead of redirecting them to the site :/

**Comment by KasRoudra** [comment]
@oaosdpo Did you started php server?

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-03 9 15 45 PM](https://user-images.githubusercontent.com/80654652/144693386-1fe817e0-4024-425d-a391-70aef88994e5.png)

**Comment by oaosdpo** [comment]
when i click run nothing happens what am i supposed to do?

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-03 9 20 29 PM](https://user-images.githubusercontent.com/80654652/144693506-52ae7974-373c-45f8-b3df-f4ecafce99a2.png)

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-03 9 20 46 PM](https://user-images.githubusercontent.com/80654652/144693512-d7757ac2-96a2-4b86-8527-940ac6690989.png)

**Comment by oaosdpo** [comment]
php not working either

**Comment by oaosdpo** [comment]
I am trying to make the code by unzipping all the files into a new and fresh repository (no pyphisher) and have it run on a domain https://accounts.rockstarbruh1.repl.co/ and when the victim enters the details it saves to the repo and redirects them to an after page

**Comment by oaosdpo** [comment]
but i've been trying to do that but all it does is save the login.php to their computer instead of redirecting to the after site i've tried it myself.

**Comment by oaosdpo** [comment]
i dont wanna use 000webhost it works perfectly fine and redirects afterwards but it has a watermark at the bottom and they can notice it easily and the only way to remove it is to pay when on replit i can do it for free. do you have a fix?

**Comment by oaosdpo** [comment]
and thank you for helping me

**Comment by KasRoudra** [comment]
I've created a repl for you. Simply run it!
[https://replit.com/@KasRoudra/test](https://replit.com/@KasRoudra/test)

**Comment by oaosdpo** [comment]
thank you so much :) it works perfectly and the way that I wanted it to as well. This is perfect! Thank you!

**Comment by KasRoudra** [comment]
Welcome!
