### ISSUE TITLE
how to use pyphisher and how youre phisihing page

### ISSUE THREAD

**Issue by livinglife33** [KasRoudra/PyPhisher#170]
hey i know how to make the phishing page but dont know how to host my page on the regluar web browsers help me please and thank you !

**Comment by KasRoudra** [comment]
@livinglife33 Websites can't be hosted on browser. Either host in local device and then start port forwarding or upload website files into some hosting service

**Comment by livinglife33** [comment]
And how would I do that brother I'm new to this can u help me

**Comment by Ghostsarah0042** [comment]
dm

**Comment by KasRoudra** [comment]
@livinglife33 That's your concern, try to learn. A lot of resources are available

**Comment by livinglife33** [comment]
> dm 
> 

How do I dm u ion how to use this app
