### ISSUE TITLE
Bro plz fix this

### ISSUE THREAD

**Issue by Dstar001** [KasRoudra/PyPhisher#171]
Download failed due to: HTTPSConnectionPool(host='lxpdownloads.sgp1.digitaloceanspaces.com', port=443): Max retries exceeded with url: /downloads/loclx-linux-arm64.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x75e0826820>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by KasRoudra** [comment]
@Dstar001 Retry when you have a good internet speeed or run [MaxPhisher](https://github.com/KasRoudra/MaxPhisher)
