### ISSUE TITLE
Ngrok problem

### ISSUE THREAD

**Issue by rockmarse** [KasRoudra/PyPhisher#172]
Hi dev ! Great effort but thier is a problem faced by me I used ngrok , first of all it went well but later my host was banned and cant use the ngrok while for cloudfred the browser flags  the link as phishing and stops the victim to visit it .. Is there any other way please let me know ❣❣

**Comment by KasRoudra** [comment]
@rockmarse What about localhostrun links?

**Comment by rockmarse** [comment]
They dont appear

**Comment by KasRoudra** [comment]
@rockmarse Try troubleshooting with `python3 pyphisher.py -e lhr`
