### ISSUE TITLE
When running any operation, returns a perm error

### ISSUE THREAD

**Issue by pastloves** [KasRoudra/PyPhisher#176]
This is what is returning when running any operation.

[•] Initializing PHP server at localhost:8080....
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/~~~~~~/PyPhisher/pyphisher.py:1363 in <module>                                           │
│                                                                                                  │
│   1360                                                                                           │
│   1361 if __name__ == '__main__':                                                                │
│   1362 │   try:                                                                                  │
│ ❱ 1363 │   │   main_menu()                                                                       │
│   1364 │   except KeyboardInterrupt:                                                             │
│   1365 │   │   pexit()                                                                           │
│   1366 │   except Exception as e:                                                                │
│                                                                                                  │
│ /Users/~~~~~~/PyPhisher/pyphisher.py:1221 in main_menu                                          │
│                                                                                                  │
│   1218 │   │   │   else:                                                                         │
│   1219 │   │   │   │   redirect_url = input(f"\n{ask}{bcyan}Enter redirection url{bcyan}[{red}p  │
│   1220 │   │   write_redirect(redirect_url)                                                      │
│ ❱ 1221 │   server()                                                                              │
│   1222                                                                                           │
│   1223 # Start server and tunneling                                                              │
│   1224 def server():                                                                             │
│                                                                                                  │
│ /Users/~~~~~~/PyPhisher/pyphisher.py:1235 in server                                             │
│                                                                                                  │
│   1232 │   for logfile in [php_file, cf_file, lx_file, lhr_file]:                                │
│   1233 │   │   delete(logfile)                                                                   │
│   1234 │   │   if not isfile(logfile):                                                           │
│ ❱ 1235 │   │   │   mknod(logfile)                                                                │
│   1236 │   php_log = open(php_file, "w")                                                         │
│   1237 │   cf_log = open(cf_file, "w")                                                           │
│   1238 │   lx_log = open(lx_file, "w")                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
PermissionError: [Errno 1] Operation not permitted

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/~~~~~/PyPhisher/pyphisher.py:1367 in <module>                                           │
│                                                                                                  │
│   1364 │   except KeyboardInterrupt:                                                             │
│   1365 │   │   pexit()                                                                           │
│   1366 │   except Exception as e:                                                                │
│ ❱ 1367 │   │   exception_handler(e)                                                              │
│   1368                                                                                           │
│   1369 # If this code helped you, consider staring repository. Your stars encourage me a lot!    │
│                                                                                                  │
│ /Users/~~~~~~/PyPhisher/pyphisher.py:478 in exception_handler                                   │
│                                                                                                  │
│    475 │   │   message = str(e).split("(")[0]                                                    │
│    476 │   else:                                                                                 │
│    477 │   │   message = str(e)                                                                  │
│ ❱  478 │   line_no = lines_arr[len(lines_arr) - 1]                                               │
│    479 │   lines_no = ", ".join(lines_arr)                                                       │
│    480 │   print(f"{error}{name}: {message} at lines {lines_no}")                                │
│    481                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
IndexError: list index out of range

**Comment by KasRoudra** [comment]
@pastloves Mac users should run it in docker
