### ISSUE TITLE
custom webpage not reflecting creds on the tool.

### ISSUE THREAD

**Issue by championboi** [KasRoudra/PyPhisher#177]
Hi, I'm a big fan of the tool. fun tool, ingenious even. However I'm having trouble harvesting creds as they are not reflecting on the tool as they should. The templates however are working perfectly. Kindly help me know where the issue might be. Also how to add a redirecting link to my custom webpage. Thanks in advance.

**Comment by Ndegwadavid** [comment]
Hello for me what I do is I host the site on my localhost and set port to
8080.

Then I go to grabify which is a url link generator and redirector.

I paste the link for my local host for example http:127.0.7.0:8080

Paste it and grabify will generate the link for redirection.you can
customize the link too.

Right now am in bed I have shutdown machine..try and if it works #happy
coding

Get in touch too for where you will be stuck

**Comment by KasRoudra** [comment]
@championboi You haven't configured php files with your html form. So, you are not getting credentials. Also, you have to edit `login.php` to work with redirection

**Comment by Ndegwadavid** [comment]
Woooooh
Thanks for that too..
Send me your GitHub username I add you as my contributor we can work in it.
Work on it and commit it I'll appreciate.

I have made the redirections.

I thought you were asking me on the Pyphisher tool. For hacking...

Send me your GitHub usermame I add you as my contributor.

Thank you

**Comment by championboi** [comment]
Thanks you guys, I'll try sort this out then I'll tell you when I get successful.
