### ISSUE TITLE
Bypass this cookies page

### ISSUE THREAD

**Issue by abubasith456** [KasRoudra/PyPhisher#178]
How to bypass this cookis page... When im trying to open link. Its how some cookies page first

![Uploading Screenshot_2022-12-09-12-22-25-637_com.android.chrome.jpg…]()

**Comment by KasRoudra** [comment]
@abubasith456 That's beyond our scope. We have no control over victim browser. You may try a different url or buy some subscription in ngrok/loclx for better link
