### ISSUE TITLE
Error while using Discord.

### ISSUE THREAD

**Issue by Souparno10** [KasRoudra/PyPhisher#179]
"PermissionError: [Errno 13] Permission denied at lines 1366, 1224, 1330, 1343, 423" error is coming when one victim's ip is coming. The credentials also aren't saved in cred.txt. Please fix.

**Comment by KasRoudra** [comment]
@Souparno10 Your OS/distro?

**Comment by Souparno10** [comment]
Kali Linux Azure Virtual Machine connected using RDP protocol and xrdp. Also Netflix, Facebook (Traditional), etc. are also not working

**Comment by KasRoudra** [comment]
@Souparno10 If one doesn't work, every other won't work. It's not written to run on azure. Run in linux/docker/android
