### ISSUE TITLE
browsers show warning about the website

### ISSUE THREAD

**Issue by niemajak900** [KasRoudra/PyPhisher#18]
created link by the tool, pasted into browser and the browser give warning that somebody might want to trick me.
it would be useful it the custom link server would be changed to something else for example: cloudflare

**Comment by KasRoudra** [comment]
PyPhisher already generates links of two server, ngrok and cloudflared. We cannot solve browser warning. It will always cause in secured browsers.

**Comment by niemajak900** [comment]
ok, does anyone have pornhub login template?
