### ISSUE TITLE
Discord Option Number 64

### ISSUE THREAD

**Issue by fourletterbackup** [KasRoudra/PyPhisher#183]
Discord or number 64 is broken won’t work when going to the link everything ive used so far works perfectly just discord option and it’s url doesn’t work

**Comment by KasRoudra** [comment]
@fourletterbackup Attach a screenshot

**Comment by fourletterbackup** [comment]
> @fourletterbackup Attach a screenshot

![image](https://user-images.githubusercontent.com/121063481/210154159-e92c9580-7189-4129-8e09-c6d8d0d03387.jpeg)

**Comment by fourletterbackup** [comment]
![image](https://user-images.githubusercontent.com/121063481/210154211-76e0d75f-d3a3-470c-abe1-81c5e81d4652.jpeg)
![image](https://user-images.githubusercontent.com/121063481/210154220-2e80fdf6-8c0f-4520-a140-f22d60bb27f7.jpeg)

**Comment by athul007a** [comment]
Try to use any other  server to host your Phishing link

**Comment by fourletterbackup** [comment]
That doesn't work

**Comment by KasRoudra** [comment]
@fourletterbackup You're right. I've found the issue. It will be fixed tomorrow

**Comment by fourletterbackup** [comment]
> @fourletterbackup You're right. I've found the issue. It will be fixed tomorrow

Just let me know when fixed

**Comment by KasRoudra** [comment]
@fourletterbackup Run `rm -rf ~/.websites`
