### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by dpagz3** [KasRoudra/PyPhisher#184]
I get the following error

error.log 
File is not a zip file
File is not a zip file
File is not a zip file

**Comment by dvhebesha** [comment]
Bro This Project  Now Under Another Name Download and use the other one

https://github.com/KasRoudra/MaxPhisher

**Comment by dpagz3** [comment]
Thanks man 👍


 
 
  On Mon, Jan 2, 2023 at 23:53, ***@***.***> wrote:   


Bro This Project Now Under Another Name Download and use the other one

https://github.com/KasRoudra/MaxPhisher
