### ISSUE TITLE
[!] Unsupported package manager, Install packages manually.

### ISSUE THREAD

**Issue by spajkr** [KasRoudra/PyPhisher#187]
![image](https://user-images.githubusercontent.com/122126614/212758698-08c20681-25f9-4acd-9038-f1a4cec5cce0.png)

**Comment by spajkr** [comment]
Help please i have windows

**Comment by KasRoudra** [comment]
@spajkr https://github.com/KasRoudra/PyPhisher#support
Run in docker

**Comment by spajkr** [comment]
How do I do this?

**Comment by spajkr** [comment]
![image](https://user-images.githubusercontent.com/122126614/212874812-54c8d886-62d3-4420-8bc3-9d6e7283ac7c.png)

**Comment by KasRoudra** [comment]
@spajkr Install docker. A lot of tutorials are available on youtube for it. Then grab the docker commands from pyphisher dock
