### ISSUE TITLE
running the tool

### ISSUE THREAD

**Issue by 1wickedwizard1** [KasRoudra/PyPhisher#188]
python3 pyphisher.py

after entering this command i get this below error 

requests cannot be installed! Install it manually by 'pip3 install requests'

it shows the same error even after typing it manually.

**Comment by KasRoudra** [comment]
@1wickedwizard1 Attach a screenshot of typing that manually

**Comment by 1wickedwizard1** [comment]
![VirtualBox_kali-linux-2022 4-virtualbox-amd64_23_01_2023_14_55_18](https://user-images.githubusercontent.com/123071327/214005678-5a4723e2-e6f6-4ef1-82f2-a576962beb00.png)

**Comment by KasRoudra** [comment]
@1wickedwizard1 Run `sudo pip3 install rich requests bs4`
