### ISSUE TITLE
Termux & ISH

### ISSUE THREAD

**Issue by KeparYTbcc** [KasRoudra/PyPhisher#19]
hi I wanted to know how should we use this tool on those Linux shell for Android and iso
(Termux, android)
(ISH, IOS)
thank you

**Comment by KasRoudra** [comment]
@KeparYTbcc You can watch this [tutorial](https://rebrand.ly/pyphishervideo). Termux is shown in that

**Comment by KeparYTbcc** [comment]
![Screenshot_20211207_112307_com.termux.jpg](https://user-images.githubusercontent.com/67996155/145067062-8ccc4b1c-9e56-4ec1-a524-27b451d0e50a.jpg)

**Comment by KeparYTbcc** [comment]
> ![Screenshot_20211207_112307_com.termux.jpg](https://user-images.githubusercontent.com/67996155/145067062-8ccc4b1c-9e56-4ec1-a524-27b451d0e50a.jpg)


shh, don't talk about my keyboard

**Comment by KasRoudra** [comment]
@KeparYTbcc Maybe your internet is slow. Try again with cellular data

**Comment by KeparYTbcc** [comment]
still not

- Kepar
________________________________

**Comment by KasRoudra** [comment]
Run it on https://replit.com
