### ISSUE TITLE
ERR_NGROK_3208

### ISSUE THREAD

**Issue by AkhyarAzamta** [KasRoudra/PyPhisher#190]
ERR_NGROK_3208
The account associated with this hostname has been banned. We've determined this account to be in violation of ngrok's terms of service. If you are the account owner and believe this is a mistake, please contact support@ngrok.com.32

**Comment by KasRoudra** [comment]
@AkhyarAzamta This isn't any issue of PyPhisher. Misuse of ngrok url leaded to this. Open a new account and submit new token
