### ISSUE TITLE
instalation probleme on kalilinux

### ISSUE THREAD

**Issue by neogen737** [KasRoudra/PyPhisher#195]
hello please need help
i can't install PYPHISHER, i did all the steps but nothing, this is the error message

Traceback (most recent call last):
  File "/root/PyPhisher/pyphisher.py", line 92, in <module>
    from smtplib import SMTP_SSL as smtp
ImportError: cannot import name 'SMTP_SSL' from 'smtplib' (/usr/local/lib/python3.10/smtplib.py)

**Comment by KasRoudra** [comment]
@neogen737 Re-install python. If the issue persists, build python3 from source

**Comment by neogen737** [comment]
Hello, please how to build python from source please

**Comment by KasRoudra** [comment]
@neogen737 https://github.com/python/cpython#build-instructions
