### ISSUE TITLE
After some time, the link to the site does not open

### ISSUE THREAD

**Issue by gamalulik** [KasRoudra/PyPhisher#198]
After some time of the script, the links that it issues stop working.

Error in the browser `DNS_PROBE_FINISHED_NXDOMAIN`

Which service is best to buy a subscription to or with which parameters to run the script so that the link works for several days and collects information about visitors

**Comment by Wasifsheikh01** [comment]
> @gamalulik As soon as you close pyphisher, the links become invalid. I suggest buying ngrok

On ngrok its is written there for free sign up account tunneling services are free for all time there is restrictions for anonymous accounts.
