### ISSUE TITLE
Python Errors

### ISSUE THREAD

**Issue by DCSanyain** [KasRoudra/PyPhisher#199]
For context I am running Ubuntu in a proot-distro environment in Termux. In Ubuntu I tried to install PyPhisher and I got a lot of errors.
![Screenshot_20230222_012059_Termux](https://user-images.githubusercontent.com/81364475/220530257-396bb52f-d4e1-4daf-876b-ba91ef752c40.jpg)

**Comment by KasRoudra** [comment]
@DCSanyain Add plain text of errors or at least a screenshot😕

**Comment by KasRoudra** [comment]
@DCSanyain It's an issue of your pip. Update it or use in termux directly

**Comment by DCSanyain** [comment]
Thank you very much! I wish for you to have a good day and I believe you can go very far in life 😊
