### ISSUE TITLE
File is not a zip file

### ISSUE THREAD

**Issue by keremsrms0721** [KasRoudra/PyPhisher#200]
sudo python ./pyphisher.py

[+] Please wait!

[!] File is not a zip file

I'm getting like this error ? There is a solution ??

**Comment by KasRoudra** [comment]
@keremsrms0721 Partial download. Run `rm -rf *.zip`

**Comment by keremsrms0721** [comment]
> @keremsrms0721 Partial download. Run `rm -rf *.zip`

I removed everthing and used directly run , it worked thanks ! ;)
