### ISSUE TITLE
how to you create a custom site using option 78

### ISSUE THREAD

**Issue by AlphaOsiris** [KasRoudra/PyPhisher#206]
im having trouble trying to understand the custom option no matter what i put it says "Directory do not exists!"

**Comment by KasRoudra** [comment]
@AlphaOsiris That's for advanced users who knows web development to build phishing site or user who has collected some other phishing site

**Comment by KasRoudra** [comment]
@KasRoudra I know. It's not something you can learn overnight. You have to spend hours and hours daily. Then after couple of months, you'll be able to build one

**Comment by AlphaOsiris** [comment]
where can i start? i cant take the html files from google

**Comment by KasRoudra** [comment]
@AlphaOsiris Only html files won't work for phishing. You have to add php files too. Additionally it may require javascript or css
