### ISSUE TITLE
PermissionError in Mac OS 

### ISSUE THREAD

**Issue by SalemAttas** [KasRoudra/PyPhisher#209]
Hey! 
Loved what you did with this project but I'm facing the same error over and over again,
it goes as follows:
 PermissionError: [Errno 1] Operation not permitted at lines 1562, 1303, 13
![Screenshot 2023-03-09 at 9 45 53 PM]

I've given the terminal permission and looked at StackOverflow for solution and it did nothing.

could you help me out with this?

![Screenshot 2023-03-09 at 9 46 25 PM](https://user-images.githubusercontent.com/73492046/224124799-5534993d-d0b8-4a46-92f8-43bc07c270a2.png)

**Comment by KasRoudra** [comment]
@SalemAttas It's a mac terminal issue and not relavant to just maxphisher. Some other scripts will also fail. Mac users should run it in docker or virtualbox.
