### ISSUE TITLE
running program in two different terminals

### ISSUE THREAD

**Issue by niemajak900** [KasRoudra/PyPhisher#21]
hi just wondering if I can run this program in one terminal and in another one at the same time so I can run two different campaigns at the same time. or will I face some issues in between?

**Comment by KasRoudra** [comment]
@niemajak900 Yeap, you'll face. Because every campaign will try to connect with port 8000. One will succeed, another will fail. So, you can run only one pyphisher at a time.

**Comment by niemajak900** [comment]
ok thanks :)
