### ISSUE TITLE
NGROK LINK WONT GENERATE

### ISSUE THREAD

**Issue by CronosYT** [KasRoudra/PyPhisher#214]
How Do I put a different NGROK token IT WONT GENERATE NGROK LINK
------------------------------------------------------------------------------------------------------------------------------------------------------
PyPhisher IS NOT GENERATING NGROK LINK
PKELASES ANY FIX :dDDD
Im depressed
- Ngrok link does not generate
- when i do ngrok http 8080 it just takes me to console but that link does not work
- HELP

**Comment by KasRoudra** [comment]
@CronosYT Run `rm -rf ~/.config/ngrok` and start pyphisher again. It will ask for token again, enter latest password

**Comment by CronosYT** [comment]
> @CronosYT Run `rm -rf ~/.config/ngrok` and start pyphisher again. It will ask for token again, enter latest password

Okay ima try one sec

**Comment by CronosYT** [comment]
> @CronosYT Run `rm -rf ~/.config/ngrok` and start pyphisher again. It will ask for token again, enter latest password

It aint workin
Only LocalHostRun is showing
![image](https://user-images.githubusercontent.com/127824294/225394644-40b0db5d-644e-418e-b2f3-51de79608276.png)

**Comment by CronosYT** [comment]
so??

**Comment by CronosYT** [comment]
> @CronosYT Run `rm -rf ~/.config/ngrok` and start pyphisher again. It will ask for token again, enter latest password

dude actually please help meh

**Comment by KasRoudra** [comment]
@CronosYT 
1.Run `~/.tunneler/ngrok http 8080` and send screenshot. 
2.Run `cat ~/.tunneler/cf.log` and copy the outputs pasting here

**Comment by CronosYT** [comment]
the first command
![image](https://user-images.githubusercontent.com/127824294/225407236-504b8c68-e0f8-4617-85d3-e01506e83fc5.png)

the 2nd one
![image](https://user-images.githubusercontent.com/127824294/225407396-4b8e7822-6e15-4634-ae9e-745f894a5f56.png)

**Comment by CronosYT** [comment]
> @CronosYT 1.Run `~/.tunneler/ngrok http 8080` and send screenshot. 2.Run `cat ~/.tunneler/cf.log` and copy the outputs pasting here

the first command
![image](https://user-images.githubusercontent.com/127824294/225407645-048bad78-a32b-4f15-8ee8-5f064548c58c.png)


the 2nd one
![image](https://user-images.githubusercontent.com/127824294/225407670-7602fcca-2224-46e0-9de9-e8219e9bbee4.png)


@CronosYT

 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>

**Comment by CronosYT** [comment]
OMG THANK YOU SO MUCH BRO

**Comment by CronosYT** [comment]
> @CronosYT 1.Run `~/.tunneler/ngrok http 8080` and send screenshot. 2.Run `cat ~/.tunneler/cf.log` and copy the outputs pasting here

YOU ARE A LIFE SAVER BRO I LVOE U THANKS :dDDD

**Comment by KasRoudra** [comment]
@CronosYT If it is fixed, close the issue
