### ISSUE TITLE
Hosting not working 

### ISSUE THREAD

**Issue by Wasifsheikh01** [KasRoudra/PyPhisher#215]
Even after using ngrok token its not working before its working now showing errors etc

**Comment by KasRoudra** [comment]
@Wasifsheikh01 add details of error

**Comment by Wasifsheikh01** [comment]
> @Wasifsheikh01 add details of error

Its showing tunneling failed use your own tunneling services on port 8080

**Comment by KasRoudra** [comment]
@Wasifsheikh01 Attach a full screenshot

**Comment by Wasifsheikh01** [comment]
> @Wasifsheikh01 Attach a full screenshot

![IMG_20230319_201620.jpg](https://user-images.githubusercontent.com/102783831/226183943-5fc0b6bd-fc5c-43a7-8154-5cc6768e115a.jpg)

![IMG_20230319_201533.jpg](https://user-images.githubusercontent.com/102783831/226183945-32c5a9af-6c9d-4ce3-b2ba-cb916d9c453a.jpg)

**Comment by KasRoudra** [comment]
@Wasifsheikh01 Test the state of ngrok by running `~/.tunneler/ngrok http 8080`. Add a screenshot of that. And for cloudflared, it is a temporary issue. It gets fixes automatically within hours

**Comment by karthikvijay0710** [comment]
its not giving me the ngrok link even i given the ngrok token to it
and its only giving me the local links
