### ISSUE TITLE
pyphisher not booting

### ISSUE THREAD

**Issue by sanjay-sai** [KasRoudra/PyPhisher#217]
it take too much of time to boot like one to two hrs.

**Comment by KasRoudra** [comment]
@sanjay-sai Your os/distro? Python version?

**Comment by sanjay-sai** [comment]
I am using Kali Linux

**Comment by KasRoudra** [comment]
@sanjay-sai Try to run it with a vpn

**Comment by sanjay-sai** [comment]
Ok
