### ISSUE TITLE
I am getting error after running python3 pyphisher.py

### ISSUE THREAD

**Issue by shk34** [KasRoudra/PyPhisher#219]
When i run python3 pyphisher.py ,i am getting the below error
[!] Download failed due to: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max r
tries exceeded with url: /KasRoudra/files/main/ngrok/ngrok-v3-stable-linux-amd64.tgz (Caused by N
ewConnectionError(*<urllib3.connection.HTTPSConnection object at 0x7f68ece410f0>: Failed to establ
ish a new connection: [Errno 101] Network is unreachable"))
<img width="1177" alt="Screenshot 2023-03-26 at 4 05 47 PM" src="https://user-images.githubusercontent.com/128985538/227783506-3b2ce27d-4c77-4259-b374-9583d532608c.png">

**Comment by KasRoudra** [comment]
@shk34 Poor internet speed. Try again later
