### ISSUE TITLE
Can you make a login page for Amino Apps?

### ISSUE THREAD

**Issue by oaosdpo** [KasRoudra/PyPhisher#22]
https://aminoapps.com/login this site right here but make facebook and google (the option the person has to login to their account) redirect to a replit site and give that a phishing code? the phone and email are within the page so there isn't a need for that.

**Comment by KasRoudra** [comment]
@oaosdpo You need total three pages. One is fake amino page containing fake facebook link and fake google link. Other two pages are fake login page of facebook and google. Am I right?

**Comment by oaosdpo** [comment]
yes

**Comment by oaosdpo** [comment]
at least when you click facebook it redirects to facebook fake screen and when its google it redirects to google fake screen if someone logs in with other email it stays on amino page same with phone number but gets logged and is redirected to the aftersite

**Comment by oaosdpo** [comment]
and on replit specifically

**Comment by KasRoudra** [comment]
@oaosdpo What about redirection after google/facebook login?

**Comment by oaosdpo** [comment]
same for that it gets redirected to an aftersite

**Comment by oaosdpo** [comment]
both of them is same

**Comment by KasRoudra** [comment]
@oaosdpo Okay, I am setting redirection to amino homepage

**Comment by KasRoudra** [comment]
[amino.zip](https://github.com/KasRoudra/PyPhisher/files/7700359/amino.zip)
Create a repl with language `php web server`. Then upload and unzip it. Run the repl

**Comment by oaosdpo** [comment]
the page is working fine but ''login with phone'' and ''login with email'' don't have their functions

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-12 10 54 09 PM](https://user-images.githubusercontent.com/80654652/145749849-ab7c625b-50d7-4673-bc87-7aaac98e86b4.png)

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-12 10 54 25 PM](https://user-images.githubusercontent.com/80654652/145749875-dada5a71-983e-4485-b925-37aa7693451f.png)

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-12 10 54 44 PM](https://user-images.githubusercontent.com/80654652/145749901-015b6613-0c29-44c0-9d28-03a03ebc4262.png)

**Comment by oaosdpo** [comment]
when you click them your supposed to be redirected to a page that looks like this but it's still on the same site

**Comment by oaosdpo** [comment]
![Screenshot 2021-12-12 10 55 29 PM](https://user-images.githubusercontent.com/80654652/145749970-1ac5e993-6471-43da-acb4-b5650e4a8fff.png)
![Screenshot 2021-12-12 10 55 25 PM](https://user-images.githubusercontent.com/80654652/145749972-81364320-6d55-4bb8-9d0b-da33e4bfbf67.png)

**Comment by oaosdpo** [comment]
i wanna have those functions too just in case because i could never know

**Comment by oaosdpo** [comment]
what they would use

**Comment by oaosdpo** [comment]
and when they click ''all sign in options'' if they accidentally press it it brings them back onto the login screen

**Comment by oaosdpo** [comment]
i ran it in the replit and everything seems to be working fine but those seem to be the only ones missing their function

**Comment by KasRoudra** [comment]
> @oaosdpo You need total three pages. One is fake amino page containing fake facebook link and fake google link. Other two pages are fake login page of facebook and google. Am I right?

Here you said yes. So I didn't work on others. Okay, soon I will work on those too

**Comment by oaosdpo** [comment]
okay thank you and sorry for not being specific

**Comment by KasRoudra** [comment]
@oaosdpo After configuring facebook and google that options really become obsolete. Maybe some javascript is interfering in login. I couldn't fix it. Sorry

**Comment by oaosdpo** [comment]
can you try to give the email/phone button a google login function? not the actual page, but in google when you click next it's supposed to show the password screen. i want it to show the email and screen after you click ''phone'' or ''email''. can you try that?

**Comment by oaosdpo** [comment]
After you click ''sign in with email'' or ''sign in with phone'' you get a screen that looks like this 

> ![Screenshot 2021-12-12 10 55 29 PM](https://user-images.githubusercontent.com/80654652/145749970-1ac5e993-6471-43da-acb4-b5650e4a8fff.png) ![Screenshot 2021-12-12 10 55 25 PM](https://user-images.githubusercontent.com/80654652/145749972-81364320-6d55-4bb8-9d0b-da33e4bfbf67.png)

**Comment by oaosdpo** [comment]
the login link doesn't change like how google doesn't change when you press next it stays on the same page.. can you give it that function? and when you click on these all others are hidden unless you go back and press ''all sign in options'' and that's when they show up again and serve their basic functions.

**Comment by KasRoudra** [comment]
@oaosdpo There is something wrong with this page. Even if I download the exact source code, those phone/email login buttons do not work!

**Comment by oaosdpo** [comment]
okay well thank you for the help i will mess around with the code myself or try to find some kind of script that gives it that page after a click

**Comment by oaosdpo** [comment]
i really appreciate it

**Comment by KasRoudra** [comment]
Welcome
