### ISSUE TITLE
Please remove ngrok as a tunneling option as this tool violates the terms of service

### ISSUE THREAD

**Issue by lee-tschetter-ngrok** [KasRoudra/PyPhisher#220]
PM for ngrok here. This tool directly violates the ngrok Terms of Service even when used for educational purposes only. We kindly request that ngrok be removed as an option in your tool.

To learn more about how ngrok combats abuse, see https://ngrok.com/abuse and https://ngrok.com/tos .

- ngrok is not anonymous and cannot be used to hide your identity. 
- ngrok directly exposes your public IP address to anyone who sees the ngrok url you send them and in an http header.
- ngrok will ban your account if you use this tool.
- ngrok adds an interstitial page to all requests warning anyone viewing the page that the site is hosted by ngrok.

Code with ngrok removed for diff:
[pyphisher.py.txt](https://github.com/KasRoudra/PyPhisher/files/11081429/pyphisher.py.txt)

**Comment by KasRoudra** [comment]
@lee-tschetter-ngrok Okay, I got it. I am working on the update. It will arrive in 2/3 days

**Comment by lee-tschetter-ngrok** [comment]
That's great to hear and much appreciated!

**Comment by KasRoudra** [comment]
@lee-tschetter-ngrok Have a recheck, if I have missed something

**Comment by lee-tschetter-ngrok** [comment]
Thank you @KasRoudra. Please also remove the ngrok references in your https://github.com/KasRoudra/MaxPhisher repo.
