### ISSUE TITLE
Terminal lacks file/Folder permission//What does it mean?

### ISSUE THREAD

**Issue by pr0t1gy** [KasRoudra/PyPhisher#227]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/128764363/230704628-d622667e-ea5c-41a3-949e-3dc485cf4574.png">
I used sudo and even chmod 777
What does it mean?
Thank you and great script

**Comment by KasRoudra** [comment]
@pr0t1gy Most mac terminals have this isssue. As suggested, you should run it from docker

**Comment by pr0t1gy** [comment]
@KasRoudra Thank you for the response. I was trying to the solve file/folder permission issue without a docker but failed.

The docker worked perfectly though

**Comment by KasRoudra** [comment]
@pr0t1gy I can't test it on mac so the troubleshooting is also not possible. You may search **PermissionError in mac terminal** on google try some of the solutions suggested

**Comment by Dominator200** [comment]
I was looking around a bit and the major problem was that the .log files weren’t there. I’m kinda stuck bc I don’t want to reverse engineer the whole thing, but maybe you know something.. Could be a linux only command or something like that
