### ISSUE TITLE
i found something 

### ISSUE THREAD

**Issue by oaosdpo** [KasRoudra/PyPhisher#23]
hi again this is about the Amino Apps page again. I was going into Javascript console and when I clicked ''sign in with email'' or ''phone'' and then click ''all sign in options'' to go back to the screen i would get this in the console. 
![Screenshot 2021-12-17 11 25 37 PM](https://user-images.githubusercontent.com/80654652/146628865-0990bb7a-ec3d-4e00-bb14-03e6221b2edc.png)
![Screenshot 2021-12-17 11 28 56 PM](https://user-images.githubusercontent.com/80654652/146628879-cb7c8cc2-f602-47dc-bc3e-9473a65eb4b8.png)

it seems to be running some sort of script that takes me back to the page. so i clicked on the hyperlink text and it and pressed the arrow on the ''static/img'' and it has all the files from the page it takes you from logging in. and beneath all the files it has (index) can there be some way to plug this into the page and test it to see if it will work this time?

**Comment by oaosdpo** [comment]
and its not an error don't worry about that I think it means the script is working but can you download the files and put it into the phishing page and see if it will work? im not good with this kinda stuff

**Comment by oaosdpo** [comment]
Also I made an account on Amino to see what would happen in the console as I logged in. This happened.


https://user-images.githubusercontent.com/80654652/146629281-941336f0-ba06-428a-9368-811df535a276.mp4

**Comment by oaosdpo** [comment]
the ones before the change aren't from logging in. when they change that's when i logged in. that's by default by going to the login page

**Comment by KasRoudra** [comment]
@oaosdpo I can work on those steps after the phone/email login button works. But currently the source code I've, doesn't provide a working button. As you can see, after the button click almost a new window appears but the url doesn't change. I've no idea how a button can act in such way(buttons should contain hyperlink, clicking them should change url) and thus can't edit it.

**Comment by oaosdpo** [comment]
I think it works like those Youtube comments do. When there is a thread all you have to click on is ''show'' to show the comments. The link doesn't change whatsoever because you would still be on the same youtube video. I think it works like that?

**Comment by oaosdpo** [comment]
Or I think that its less basic with a simple click it switches it's page and then after the login it redirects you

**Comment by oaosdpo** [comment]
because the login screen had javascript built into it

**Comment by KasRoudra** [comment]
@oaosdpo I know how that youtube comments work. The comments are set to `hidden` class. When we click on show the onclick function adds `show` class and removes `hidden` class. This is done by querySelector and classList.add(). However, I couldn't find such codes and thus the problem remains

**Comment by oaosdpo** [comment]
can we try adding the codes?

**Comment by oaosdpo** [comment]
or what about when it's a scratch thing i've seen it on scratch when you code something to onclick and click a sprite it is coded to ''switch to other costume'' and thne when you click it it changes

**Comment by oaosdpo** [comment]
the button has no code whatsoever?

**Comment by KasRoudra** [comment]
@oaosdpo The button has html codes, but we are searching for related javascript which isn't present in source code. I can manually create new button(and remove old) with required functionality but the problem is I can't find the code of that new window in which the onclick will toogle

**Comment by oaosdpo** [comment]
also this is a bit unrelated but i think it could help but when i was exploring the google page i gave you i think the reason the button wasn't working at first was because when i was exploring it there was a phishing code the original creator developed and it's in the folder assets>js>custom.js where the phishing code was in custom.js and i think that most phishing codes run in .php files. maybe we can try copying the code and putting it there because the google started working after  the login.php was added.

**Comment by oaosdpo** [comment]
and the custom.js us just switched for the aminoapps page

**Comment by oaosdpo** [comment]
and if making the custom.js to php doesn't work try doing custom.js just by itself if it is not built with a function i think we have to make one? i think all you have to do is add the script in the file and href aminoapps.html or plug it in to connect with the page somehow

**Comment by KasRoudra** [comment]
@oaosdpo In that case of google's custom.js, I exactly found the variables of username and password. Later, I managed to output those variables. But in aminoapps, there is no such javascript. Wait, I am showing google's one. Now you can search for amino's one too.
![Screenshot_2021-12-20-13-34-58](https://user-images.githubusercontent.com/78908440/146729906-7f2b1b5b-6dcf-4e0c-b789-9f8a2a1823d4.jpeg)
## Look at this variables, they are already defined in Coogle's code

## So I created a function createCookie to output them
![Screenshot_2021-12-20-13-31-58](https://user-images.githubusercontent.com/78908440/146729922-eb31fe7c-ac5a-414f-93b9-94b14c1222e1.jpeg)

### This is not possible for aminoapps, because there is no direct variable

**Comment by oaosdpo** [comment]
can we try recreating the entire page, and then giving it that function? like create one of our own.

**Comment by oaosdpo** [comment]
and i found some thing else too in the code

**Comment by oaosdpo** [comment]
![image](https://user-images.githubusercontent.com/80654652/146822905-2f145b4f-0baf-4228-bd42-6af7bb974ad6.png)

**Comment by oaosdpo** [comment]
first clicking ''sign in with email'' and then clicking on ''all sign in options'' i was met with this page again. i was monitoring the console and then i clicked the little arrow next to the uncaught and then there was scripts like e.''go back' and t.emit. could the function eb within these codes? can you try downloading the coe and putting it in the page?

**Comment by oaosdpo** [comment]
i rhink the button function has to be here.

**Comment by oaosdpo** [comment]
also if you click the hyperlinks (for example e.goback login.17ef394fc.js:1 then it will bring you to application and the script will be there.

**Comment by KasRoudra** [comment]
@oaosdpo I searched for `login.17ef394fc.js` but in source code it's not present! Maybe it is serversided
![Screenshot_2021-12-21-21-06-42](https://user-images.githubusercontent.com/78908440/146952876-3e5f985e-c4b5-4b53-b450-dfccd8573acc.jpeg)
### This main.js is the only javascript in source code

**Comment by oaosdpo** [comment]
i went to aminoapps.com/login and did ctrl+U and then did ctrl+f and then in the bar i did .js and it gave me 11 results within the page

**Comment by oaosdpo** [comment]
and it's just like in the console.

**Comment by oaosdpo** [comment]
> ![image](https://user-images.githubusercontent.com/80654652/146822905-2f145b4f-0baf-4228-bd42-6af7bb974ad6.png)

but it only has 12 in the console but when i do .js on the view source it has 11.

**Comment by oaosdpo** [comment]
counting .Array.foreach it doesn't show a code (in the console) which makes 13 but it says anonymous and not giving the code at all.

**Comment by oaosdpo** [comment]
or we can try the console script above the other one by downloading the file. it's probably not js but powered by something else. you can give it a go?

**Comment by KasRoudra** [comment]
@oaosdpo I am using android. I can't use console like you. So, you have to download that js script/the original source code

**Comment by oaosdpo** [comment]
ok
