### ISSUE TITLE
Ngrok Option

### ISSUE THREAD

**Issue by fourletterbackup** [KasRoudra/PyPhisher#231]
Was Ngrok removed or what I have both local and Ngrok but Ngrok worked better can this be added back

**Comment by Codexitb** [comment]
Good day, Damn! I am having issues with ngrok on virtualbox' installed on windows 10,  but ngrok works fine on phon, how can I fix this?

**Comment by KasRoudra** [comment]
@Codexitb Ngrok is removed in last update due to request from PM of ngrok

**Comment by Codexitb** [comment]
Okay, please what other host operate alternatively to ngrok' which works perfectly with virtualbox on windows 10?
