### ISSUE TITLE
Change OTP page

### ISSUE THREAD

**Issue by MikesLanguren** [KasRoudra/PyPhisher#233]
Is it possible to change from "+1 xxx-xxx-xxxx" to a custom phone number more realistic on the OPT page? For example, the victims number is 123-123-1223 and after entering the password it would prompt for the verification code sent to the phone number, instead of having "+1 xxx-xxx-xxxx" it would be "+1 xxx-xxx-1223"

**Comment by KasRoudra** [comment]
@MikesLanguren Most of the times we don't have access to victim phone number. If you want to hardcode a number, you may replace the xxx-xxx-xxx with your desired number

**Comment by okyerejosephokraku60** [comment]
The OTP page is cool now but the CryptoAir
I sent you a MAIL using VPNCONFILES.

This should be between you and I.
Thank you
