### ISSUE TITLE
email.json is read only

### ISSUE THREAD

**Issue by SmokeV4** [KasRoudra/PyPhisher#236]
email.json is read only

**Comment by KasRoudra** [comment]
@SmokeV4 Add screenshot

**Comment by SmokeV4** [comment]
when i try to edit it it tell me to save as but i cant in the direcotry and it is read only

**Comment by KasRoudra** [comment]
@SmokeV4 Probably you have git cloned with sudo resulting the files owned by root. Run chown command to fix ownership otherwise delete the folder and clone again

**Comment by SmokeV4** [comment]
this is how i installed it:
open root terminal
cd /kali/home/Desktop thingy
git clone
python3 pyphisher.py

**Comment by KasRoudra** [comment]
@SmokeV4 Root terminal is not required. This is causing ownership conflict. Delete the folder and run all commands from user terminal

**Comment by teshabh** [comment]
when  i try to download requirement txt  it wont work even when i tried pip3

**Comment by KasRoudra** [comment]
@teshabh Send screenshot

**Comment by SmokeV4** [comment]
it says this. i put my email in the email.txt after reinstalling pyphisher without root but it does not send email and says this:
![image](https://github.com/KasRoudra/PyPhisher/assets/129429788/37cac273-b7ab-4f13-8d3f-1475d84ae041)

**Comment by SmokeV4** [comment]
> it says this. i put my email in the email.txt after reinstalling pyphisher without root but it does not send email and says this: ![image](https://user-images.githubusercontent.com/129429788/238343389-feb1ddf5-3c1c-42ed-8eeb-f5bb461acedf.png)

it says this. i put my email in the email.txt after reinstalling pyphisher without root but it does not send email and says this:
image

![image](https://github.com/KasRoudra/PyPhisher/assets/129429788/2143e6bd-c489-4771-a2f0-f75b9d376621)
