### ISSUE TITLE
it does not send details to email?????????????!!!!

### ISSUE THREAD

**Issue by SmokeV4** [KasRoudra/PyPhisher#237]
it says this. i put my email in the email.txt after reinstalling pyphisher without root but it does not send email and says this:
image

![image](https://github.com/KasRoudra/PyPhisher/assets/129429788/a816b649-f405-40f4-8c3f-9c01705d044f)

**Comment by SmokeV4** [comment]
pls anyone

**Comment by SmokeV4** [comment]
wdym by that

**Comment by SmokeV4** [comment]
im confused as to what that means can u give steps ?

**Comment by KasRoudra** [comment]
@SmokeV4 https://youtu.be/hXiPshHn9Pw

**Comment by SmokeV4** [comment]
i thought the email thing will work 24/7 if i download the file by saving the page and then publishing it but it doesn't?
is there a way i can make the page 24/7 online w email support
(ngrok and others take it down + ngrok aint workin)

**Comment by KasRoudra** [comment]
@SmokeV4 It's not possible. Your links, capturing details all will work only while the script is running.
