### ISSUE TITLE
How to open from main menu this tool in termux


### ISSUE THREAD

**Issue by lord-Hasli** [KasRoudra/PyPhisher#24]
How to open tool from main menu termux

**Comment by KasRoudra** [comment]
@lord-Hasli Your question is unclear

**Comment by lord-Hasli** [comment]
I am asking that from termux starting page which command i have to put to open  **CAMHACKR** OR **PYPHISHER**

**Comment by KasRoudra** [comment]
@lord-Hasli There is no direct way. You have to enter the directory with `cd PyPhisher` or `cd CamHacker`. Then `python pyphisher.py` or `bash ch.sh`

**Comment by lord-Hasli** [comment]
CAMHACKER NOT SHOWING LINK
![Screenshot_20220114_105349.jpg](https://user-images.githubusercontent.com/97538980/149456412-a43bb43c-de54-4d68-b4cd-fe556e2ede14.jpg)

**Comment by KasRoudra** [comment]
@lord-Hasli This is not my CamHacker🙄

**Comment by lord-Hasli** [comment]
Ok

**Comment by KasRoudra** [comment]
https://github.com/KasRoudra/CamHacker

Try this @lord-Hasli

**Comment by lord-Hasli** [comment]
![Screenshot_20220114_110529.jpg](https://user-images.githubusercontent.com/97538980/149457255-d9ef91a6-6adc-475f-9d38-0aed96f89fee.jpg)

**Comment by KasRoudra** [comment]
@lord-Hasli You need to change termux-repo to GH server. Or you can try using a vpn
