### ISSUE TITLE
Change custom link

### ISSUE THREAD

**Issue by HermesCalif** [KasRoudra/PyPhisher#250]
i wanna change the custom link, always is cloudflare per default and i wanna change for localx, is it possible?

**Comment by KasRoudra** [comment]
@HermesCalif Possible from long ago. Run with `-t` flag followed by service name. Ex: `python3 pyphisher.py -t localhostrun` or `python3 pyphisher.py -t loclx`

**Comment by HermesCalif** [comment]
it´s working thx
