### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by fourletterbackup** [KasRoudra/PyPhisher#254]
Letter Option: Location Grabber

When i type the letter L on the script i would like a location grabber when the site ask to allow location (if allowed) it sends the attacker the address or location of that specific device that allowed precise location

**Comment by KasRoudra** [comment]
@fourletterbackup A login page asking for location is completely suspicious. And to grab just the location of target you may use the location option of MaxPhisher

**Comment by pratik-reo** [comment]
Great job
