### ISSUE TITLE
My Facebook account was hacked and porn was downloaded to it

### ISSUE THREAD

**Issue by Ahmedmohamed2112** [KasRoudra/PyPhisher#257]
I need help to get my hacked Facebook account back to normal. My account has been hacked and spam has been downloaded to it, I need technical support and help to get past this issue and regain control of my account.

I am posting this description on GitHub to seek help from the developer community. I'd like to find a professional or team who can provide guidance and help recover my account and get rid of the harmful content posted on it.

So, I ask anyone who has experience in recovering hacked Facebook accounts or knows useful tools and techniques to achieve this to help me. I would appreciate any help you can give me in resolving this issue and getting my personal account back as soon as possible.

Thanks to everyone who is so nice to help me with this important matter.

**Comment by KasRoudra** [comment]
@Ahmedmohamed2112 Although it's sad but you've posted your issue in wrong place. This repo is only for phishing issues. Good luck

**Comment by Ahmedmohamed2112** [comment]
> @Ahmedmohamed2112


> @Ahmedmohamed2112على الرغم من أنه أمر محزن ، إلا أنك قمت بنشر مشكلتك في مكان خاطئ. هذا الريبو مخصص فقط لقضايا التصيد الاحتيالي. حظ سعيد

Ok, post this topic, where can I get help from?
