### ISSUE TITLE
custom link not working

### ISSUE THREAD

**Issue by ludovico1234** [KasRoudra/PyPhisher#26]
custom link is not working.
only one small part of the link is "valid
![WhatsApp Image 2022-02-15 at 13 39 13](https://user-images.githubusercontent.com/30573230/154063987-d1fc7b41-6738-4d72-bb2e-32c3e62e3fc3.jpeg)
"

**Comment by KasRoudra** [comment]
@ludovico1234 Can you give a screenshot of pyphisher when you were generating custom link?

**Comment by ludovico1234** [comment]
> @ludovico1234 Can you give a screenshot of pyphisher when you were generating custom link?
![WhatsApp Image 2022-02-15 at 14 25 55](https://user-images.githubusercontent.com/30573230/154071389-2a9612ce-a593-4abe-b37a-4aa3cc0b812b.jpeg)
![WhatsApp Image 2022-02-15 at 14 27 06](https://user-images.githubusercontent.com/30573230/154071405-d833dca0-0497-49c7-92ab-7b7a128ff98b.jpeg)
i used the option 5 = traditional instagram

**Comment by KasRoudra** [comment]
@ludovico1234 You inputted wrong domain. Domains must not contain `/`. Your custom domain should be **instagram.com**
not `instagram/account/login`

**Comment by ludovico1234** [comment]
> @ludovico1234 You inputted wrong domain. Domains must not contain `/`. Your custom domain should be **instagram.com** not `instagram/account/login`

thx now it works ;)

**Comment by KasRoudra** [comment]
@ludovico1234 So, I hope you can close this issue

**Comment by ultramax6** [comment]
hey custom url isnt loadig in other devices

**Comment by Carlos1109-kali** [comment]
Hola !! Tengo un problema con todas las herramientas que es que cuando le doy a customizar mi link me pone que "service nota avaliable" que hago ?? Estoy ahora mismo en pyphisher pero me pasa en zohisher y en maxphisher también.
