### ISSUE TITLE
Can't install requests.

### ISSUE THREAD

**Issue by shadowwaver6205** [KasRoudra/PyPhisher#260]

**Comment by KasRoudra** [comment]
@shadowwaver6205 Add screenshot

**Comment by shadowwaver6205** [comment]
![IMG_20230802_071035.jpg](https://github.com/KasRoudra/PyPhisher/assets/134183113/74ea052a-0c1e-447b-adbf-b5c9f197c471)

**Comment by KasRoudra** [comment]
@shadowwaver6205 Is it termux from play store?
