### ISSUE TITLE
Pyphiaher custom link doesn't open in victims device

### ISSUE THREAD

**Issue by mospop41** [KasRoudra/PyPhisher#266]
I am using py phisher and when I make a custom link so the victim doesn't know it is a phishing link when I send it and the victim open it nothing appear on his device and nothing appear in my terminal please fix

**Comment by KasRoudra** [comment]
@mospop41 How many times do you face this? What is your os?

**Comment by samsapi1018** [comment]
download failed when type the final command due to httpconnnectionpool

**Comment by samsapi1018** [comment]
how to fix that
