### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by naimurhossain** [KasRoudra/PyPhisher#277]
can you please fix this : ) same issue with the Max Phisher.
![Screenshot_2023-09-17_12_30_51](https://github.com/KasRoudra/PyPhisher/assets/143959186/2ef43559-1d46-4050-9228-169a5f109024)

**Comment by KasRoudra** [comment]
@naimurhossain  Upload complete screenshot. First part is missing

**Comment by naimurhossain** [comment]
![Screenshot_2023-09-19_02_11_00](https://github.com/KasRoudra/PyPhisher/assets/143959186/3459544d-2b65-4b84-8cc5-90e10370eea5)
![Screenshot_2023-09-19_02_11_37](https://github.com/KasRoudra/PyPhisher/assets/143959186/7c94ecc9-87e2-43c5-bc58-9ebb373c4ece)
![Screenshot_2023-09-19_02_11_47](https://github.com/KasRoudra/PyPhisher/assets/143959186/e7336c8b-bbef-4467-ae07-8eec6749f83e)

**Comment by naimurhossain** [comment]
still having same issue

**Comment by KasRoudra** [comment]
@naimurhossain Try from another device. This is NOT any issue of pyphisher or maxphisher
