### ISSUE TITLE
PyPhisher problem or not?

### ISSUE THREAD

**Issue by TransformerV2** [KasRoudra/PyPhisher#281]
Hello friends before I was already using PyPhisher and when I launched it it launched directly now it remains blocked for a long time on please wait and it does not launch is this normal? Kali is fully up to date then I already tried again uninstall reinstall but I don't understand why it doesn't work like before

**Comment by TransformerV2** [comment]
![Screenshot_2023-10-03_13_39_01](https://github.com/KasRoudra/PyPhisher/assets/146835942/5d9c4a2e-6589-4ecf-9f30-46e13e3a9885)

**Comment by KasRoudra** [comment]
@TransformerV2 Have you tried using a vpn? Looks like it can't connect with github which is required
