### ISSUE TITLE
Problem while creating custom link.

### ISSUE THREAD

**Issue by uniquedestiny123** [KasRoudra/PyPhisher#285]
Getting this problem while creating custom link.
How to avoid this?
![image](https://github.com/KasRoudra/PyPhisher/assets/147260612/f51c839f-3ac5-4989-84fa-ccb4b34fcfbe)

**Comment by KasRoudra** [comment]
@uniquedestiny123 Try other url shorteners or use actual urls. This url shortener is banned by instagram
