### ISSUE TITLE
Masking URL's doesn't work 

### ISSUE THREAD

**Issue by profesionalleet1337** [KasRoudra/PyPhisher#289]
Heyy, the masking option don't work ? Will it be fixed ? 
- > [?] Wanna try custom link? [y or press enter to skip] : y
[!] Service not available!

**Comment by KakaoXI** [comment]
Yes is a problem with shrtco.de, happens to me too from 2 days

**Comment by profesionalleet1337** [comment]
This was a very important addition to the tool because it did a great job. I looked in the closed issues, he said instagram banned the url shortener, but I checked 2-3 tools in git hub ( for masking ) and they don't work either. I have no idea what's going on, but I really hope the dude finds a solution or adds a new mask, because the instrument is wonderful and worth maintaining !

**Comment by profesionalleet1337** [comment]
> Yes is a problem with shrtco.de, happens to me too from 2 days

This was a very important addition to the tool because it did a great job. I looked in the closed issues, he said instagram banned the url shortener, but I checked 2-3 tools in git hub ( for masking ) and they don't work either. I have no idea what's going on, but I really hope the dude finds a solution or adds a new mask, because the instrument is wonderful and worth maintaining !

**Comment by profesionalleet1337** [comment]
@KakaoXI @KasRoudra

**Comment by KakaoXI** [comment]
Unfortunately i don't have :( i see again that api shrtco is down

**Comment by profesionalleet1337** [comment]
Hope the creator check this soon .. ! For my bad , I can't find contact with him - like somewhere to expain this .. Maybe discord channel, telegram , just some media ..

**Comment by maarsss** [comment]
@profesionalleet1337

**Comment by Spiderx11** [comment]
Any updates on this? I’m having the same issue

**Comment by profesionalleet1337** [comment]
For me - no . The creator has not updated the tool, from one -two months. So, if someone has found a solution, could write.

**Comment by profesionalleet1337** [comment]
Thanks for the quick and instant response from the creator - @KasRoudra .  The mask problem has been fixed, and the links are working fine, so far ! I wrote to him yesterday, and today the dude fixed the problem ! Once again, acknowledgements for a quick and adequate job. Thanks also to @maarsss , for leaving me the contact with which I contacted the creator !

**Comment by HermesCalif** [comment]
@KasRoudra Did you fix this with a new pyphisher update or did @profesionalleet1337  edit the setup mask?
