### ISSUE TITLE
Issue with Storage Permissions in PyPhisher

### ISSUE THREAD

**Issue by AiJuicy** [KasRoudra/PyPhisher#290]
I have been trying to use PyPhisher, and I encountered an issue related to storage permissions within Termux.

The script repeatedly asks for permission to rebuild the '~/storage' directory, even after granting the necessary permissions using 'termux-setup-storage.' I am aware that the script should rebuild its structure, but it seems to run into a loop and ultimately does not work as expected.

I have tried several times to proceed with the operation by typing 'y,' but it still does not resolve the issue. As a result, I am unable to use PyPhisher effectively.

This is the error message 👇

((( ~ $ cd PyPhisher
~/PyPhisher $ python3 pyphisher.py

[+] Please wait!

It appears that directory '~/storage' already exists.
This script is going to rebuild its structure from
scratch, wiping all dangling files. The actual storage
content IS NOT going to be deleted.

Do you want to continue? (y/n)
)))

And i have already given permission with different ways in my Termux App

I am using Termux from F-droid on Infinix Hot 12 play Android 11 , and I have followed the instructions provided in the script's documentation.
and have tried so many ways

I'm reaching out to seek your guidance or assistance in resolving this issue. If there are specific steps or modifications I need to make to use PyPhisher correctly, please let me know. Alternatively, if this is a known issue or bug, I would appreciate any insights or updates you can provide.

Thank you for your time and attention. I'm eager to utilize PyPhisher and look forward to your response.

**Comment by KasRoudra** [comment]
@AiJuicy Have you tried a restart of termux after allowing permission?
