### ISSUE TITLE
Fatal error while cloning pyphisher

### ISSUE THREAD

**Issue by Perax1** [KasRoudra/PyPhisher#295]
im getting this error : when i try to clone it

fatal: unable to access 'https://github.com/KasRoudra/PyPhisher/': Unsupported proxy syntax in 'enter_your_proxy:enter_port': Port number was not a decimal number between 0 and 65535

**Comment by KasRoudra** [comment]
@Perax1 Can you clone any other repositories?

**Comment by Perax1** [comment]
i tried ur MaxPhisher aswell it gave me the same error

**Comment by KasRoudra** [comment]
@Perax1 Appears to be issue with your git package. Uninstall git and install the latest package
