### ISSUE TITLE
Problem with custom method:PermissionError: [Errno 13] Permission denied at lines 1454, 1275, 950, 351, 351, 351, 351, 351, 347

### ISSUE THREAD

**Issue by Fahru28** [KasRoudra/PyPhisher#307]
Enter a bait sentence (Example: free-money) > free-money
[!] PermissionError: [Errno 13] Permission denied at lines 1454, 1275, 950, 351, 351, 351, 351, 351, 347

**Comment by KasRoudra** [comment]
@Fahru28 The directory you are trying to use as custom is probably owned by root user only. Copy the files to a folder in your home directory

**Comment by Fahru28** [comment]
I try /storage/primary/self/download.  It's work. Thanks
