### ISSUE TITLE
[•] Initializing PHP server at localhost:8080...[!] PHP Error

### ISSUE THREAD

**Issue by XM1N21KR1** [KasRoudra/PyPhisher#31]

**Comment by XM1N21KR1** [comment]
:(

**Comment by KasRoudra** [comment]
Run this
```
php -S 127.0.0.1:8080
```
And give screenshot

**Comment by XM1N21KR1** [comment]
> Run this
> 
> ```
> php -S 127.0.0.1:8080
> ```
> 
> And give screenshot

it work rn, nah the screenshot, i upload it on anonfiles, thankyouu You are very helpful script kiddie like me 

https://anonfiles.com/3eu4YbL6xb/crop1_jpg

**Comment by KasRoudra** [comment]
@XM1N21KR1 Like previous one, you can close this issue too

**Comment by XM1N21KR1** [comment]
> @XM1N21KR1 Like previous one, you can close this issue too

suree
