### ISSUE TITLE
How long link is valid? 

### ISSUE THREAD

**Issue by Mooood1** [KasRoudra/PyPhisher#311]
Hi 
I generate link and after couples of minute link show TUNNEL NOT FOUND ERROR 404,anyone know how to keep same link for long time?

**Comment by KasRoudra** [comment]
@Mooood1 All links expire as soon as there is a network restart/disconnect which may be caused by your celluar data or even wifi. Close of pyphisher also deactivates the link. Furthermore free services are limited. Free loclx urls last for 15 minuted and localhostrun urls for 5 minutes only
