### ISSUE TITLE
Packages manager

### ISSUE THREAD

**Issue by V4LL-3** [KasRoudra/PyPhisher#34]
It says "Unsupported package manager. Install packages manually!" How can I do this (in termux)?

**Comment by V4LL-3** [comment]
I mean, what should I download manually?

**Comment by KasRoudra** [comment]
@V4LL-3 What's your os? The packages are php, curl, wget, unzip

**Comment by V4LL-3** [comment]
Now I use ISH, on iOS. As I know it's Ubuntu based.

**Comment by V4LL-3** [comment]
![image](https://user-images.githubusercontent.com/94324321/159417075-b6196031-c156-4915-95e6-97f9b66a29be.jpeg)

**Comment by V4LL-3** [comment]
I got all the packages that are needed I guess but still doesn't working

**Comment by Mdkayes8953** [comment]
You need to enter the termux,and refresh your termux.then install all the
git..and write https://gethub.com/pkg install git.pyphisher.sh
Then,you need run all the tools.and then you can install all the uninstable
pkg..
Don't sent any mail again ....

**Comment by KasRoudra** [comment]
@Mdkayes8953 He didn't mail you. You've turned on watch for this repository and thus receiving mails

**Comment by KasRoudra** [comment]
@V4LL-3 Your terminal doesn't seem to be termux. Because latest termux uses apt, apt-get and pkg package managers. You can try downloading latest termux from fdroid
