### ISSUE TITLE
Link not working 

### ISSUE THREAD

**Issue by ZenicG** [KasRoudra/PyPhisher#36]
![hmm](https://user-images.githubusercontent.com/102261761/159803471-57de5b02-d652-4bdd-af95-3f8c99aa19e6.PNG)

I dont know why, but none of the links are workin for me. The first time I tried it was with the gmail login and it worked, but all tries after werent successful at all. pls help

**Comment by KasRoudra** [comment]
@ZenicG That's a server issue. You should try again later, or you can buy a premium plan from ngrok if you want to solve that immediately

**Comment by KasRoudra** [comment]
@ZenicG I think you can try again after a few hours

**Comment by ZenicG** [comment]
Alright thanks mate, and props for this crazy tool ❤️
