### ISSUE TITLE
Why I need to turn on my hotspot?

### ISSUE THREAD

**Issue by Bhavy11111** [KasRoudra/PyPhisher#39]
I have to send the link to a person who doesn't live in my city , Why I need to turn on my hotspot ? 
Will it log the credentials (not just the ip) if I send him the link

**Comment by KasRoudra** [comment]
@Bhavy11111 The tunneling services like ngrok and cloudflared will use hotspot. You can only skip hotspot if victim is under same LAN(WI-FI). Otherwise, you have to use hotspot and tunneling services

**Comment by Bhavy11111** [comment]
@KasRoudra That means I can't use it for someone who is not in my city currently ?

**Comment by KasRoudra** [comment]
@Bhavy11111 Without hotspot, you can't. Although in some devices ngrok and cloudflared may not require hotspot, so you can try
