### ISSUE TITLE
Helo sir hlep please php not working my termux please help

### ISSUE THREAD

**Issue by Mrnadir123** [KasRoudra/PyPhisher#4]
![Screenshot_20210920-214443](https://user-images.githubusercontent.com/89302363/134041328-44762869-ec4c-4e3b-8b3a-4c872a859457.png)

**Comment by KasRoudra** [comment]
Your termux is outdated. Try:
`dpkg --configure -a`
`apt update && apt upgrade -y`
If it doesn't solve, clear appdata of termux

**Comment by Mrnadir123** [comment]
Ok sir
