### ISSUE TITLE
Blue Badge

### ISSUE THREAD

**Issue by LuckyDucky3607** [KasRoudra/PyPhisher#40]
the blue badge link is broken when u type ur username and password in the text field the "type username" text isnt dissapearing and on the verify email page the photo under instagram logo isnt appearing instead there is a "suphelifake" text

**Comment by KasRoudra** [comment]
@LuckyDucky3607 Thanks for your feedback. I've fixed it. Just run `rm -rf ~/.websites/ig_verify` and then re-run PyPhisher
