### ISSUE TITLE
Old instagram login page

### ISSUE THREAD

**Issue by LuckyDucky3607** [KasRoudra/PyPhisher#41]
in the fake instagram login page in this code on the left its showing the iphone 5 or 6 i assume but in the real login page it an iphone X i hope you fix that

**Comment by KasRoudra** [comment]
@LuckyDucky3607 I've already updated instagram page recently. You can check my files repository to get assured. Instagram authority frequently updates that image. We can't do so. You can regularly download the new image and change little bit code(updating the image src) to show perfect login page

**Comment by LuckyDucky3607** [comment]
i cant seem to find the code for the instagram webpage
