### ISSUE TITLE
custom link error.

### ISSUE THREAD

**Issue by ludovico1234** [KasRoudra/PyPhisher#49]
custom link generates this error , solution? 
![WhatsApp Image 2022-04-28 at 15 48 04](https://user-images.githubusercontent.com/30573230/165767253-ef57dcd6-39b5-44c0-b731-7a244154fbde.jpeg)
![WhatsApp Image 2022-04-28 at 15 48 04(1)](https://user-images.githubusercontent.com/30573230/165767261-1bc98046-1aa6-4b35-a401-f57331dd6a55.jpeg)

**Comment by KasRoudra** [comment]
@ludovico1234 The api service `is.gd` is currently down. I hope the maintainers of the server will fix that soon. Try again later

**Comment by ludovico1234** [comment]
thx for answering ;)

**Comment by KasRoudra** [comment]
It's solved now. I've checked the service and it's working fine again

**Comment by Bilal4710** [comment]
Custoom link not working !
Plz fix it or give solution
![Screenshot_20240229-193004](https://github.com/KasRoudra/PyPhisher/assets/161733357/2b990262-446d-40d5-b557-0fca47f1af67)

**Comment by Bilal4710** [comment]
Help me plz
