### ISSUE TITLE
PHP Error

### ISSUE THREAD

**Issue by Ajotah98** [KasRoudra/pyphisher#5]
Hi, i have a problem running the .py on Termux.
When i select the option, the PHP tries to initialize, but then it gives PHP Error.
I have all the requerimients downloaded and upgraded.
How can i solve that?

**Comment by Ajotah98** [comment]
![IMG_20210921_180229](https://user-images.githubusercontent.com/91145535/134206003-82bbd9c8-9835-4398-a998-4663a646301f.jpg)
I paste a screenshot. It didnt give a lot of info but i Guess It helps

**Comment by KasRoudra** [comment]
Check your php status by `php -S 127.0.0.1:8080`
Let me know the result

**Comment by Ajotah98** [comment]
It seems like localhost is already on use on my phone... Do you know how can i solve?
![IMG_20210921_192505](https://user-images.githubusercontent.com/91145535/134218455-bfc23c14-ce6d-408a-a2cb-dafa16e68219.jpg)

**Comment by KasRoudra** [comment]
Simply exit termux, wait a while and reopen termux

**Comment by Ajotah98** [comment]
It didnt worked... Both of them or reinit Termux.

**Comment by KasRoudra** [comment]
Run those commands
`cd pyphisher`
`sed "s+8080+8888+g" pyphisher.py > p.py`
`rm -rf pyphisher.py && mv p.py pyphisher.py`
Then rerun pyphisher

**Comment by Ajotah98** [comment]
Hi! Idk why but the repo had been installed without a directory, only the .py archive. I re-cloned the repo and now all ok. Ty from the answers!

**Comment by Codesherman** [comment]
Hi, 
i have a problem on linux for running this program and it says php error.
Can you please help me?
Thank you in advance.

**Comment by KasRoudra** [comment]
@Codesherman 
> Check your php status by `php -S 127.0.0.1:8080` Let me know the result

**Comment by Codesherman** [comment]
[Mon Jun 13 09:53:20 2022] PHP 8.1.5 Development Server (http://127.0.0.1:8080) started

its what it says

**Comment by Codesherman** [comment]
Initializing PHP server at localhost:8080....

[!] PHP Error
php(12390): Function not implemented
php: no process found

[•] Thanks for using!



and it's what it says when i launch it

**Comment by KasRoudra** [comment]
@Codesherman Distro means the formal name of your operating system. And I asked whether you run `sudo python3 pyphisher.py` or `python3 pyphisher.py`

**Comment by alsdnrla** [comment]
File "pyphisher.py", line 914
    if (shortened:=shortener1(url)) != "":
                 ^
SyntaxError: invalid syntax





why?

**Comment by KasRoudra** [comment]
@alsdnrla Outdated python. Update to at least 3.9

**Comment by KasRoudra** [comment]
@roxtha iPhone isn't officially supported because I have no way to test/troubleshoot it. Use android/linux for best result

**Comment by fin7demon** [comment]
> 

My python has been updated and I’m using kali 2023

**Comment by KasRoudra** [comment]
@fin7demon Fake. PyPhisher has 1324 lines. It's not possible to show error in 1506 line

**Comment by fin7demon** [comment]
@KasRoudra ive tried re installing but still that error pops up. Everything is also updated. It was working then but I don’t know why. Should clean the library

**Comment by LordClutcher** [comment]
ValueError: could not convert string to float at lines 1366, 1149, 1117
In PyPhisher how could we get out of this error?

**Comment by ChosenX-byte** [comment]
i got problem . when i want to mask url something going wrong it is not working
