### ISSUE TITLE
will u be adding a 2fa page to websites like instagram, facebook or googe?

### ISSUE THREAD

**Issue by ARanonymous** [KasRoudra/PyPhisher#51]

**Comment by KasRoudra** [comment]
@ARanonymous 2FA requires a backend or sms/email api. I don't have plan of adding such features now because I am currently busy. Maybe it will be added in future

**Comment by ARanonymous** [comment]
oh okay, Advphishing has it if u want to check it out, i normally use advphishing but urs is better it's just missing 2fa that's why im asking. Love your work tho

**Comment by KasRoudra** [comment]
@ARanonymous Added!
