### ISSUE TITLE
Error pHP

### ISSUE THREAD

**Issue by AlverNL117** [KasRoudra/PyPhisher#55]
![Screenshot_2022-05-10-23-09-28-829_com.termux.jpg](https://user-images.githubusercontent.com/105335528/167767792-ec00a32e-6d02-4df6-b01f-b01aea3fb31e.jpg)

**Comment by KasRoudra** [comment]
@AlverNL117  Run `php -S 127.0.0.1:8080` and then give screenshot

**Comment by AlverNL117** [comment]
I already deleted the data several times but the problem continues and now it won't even let me install the pyphisher, I'll try to reinstall it. I download it from the Playstore or from the page f of termux?

**Comment by AlverNL117** [comment]
![Screenshot_2022-05-11-08-38-38-748_com.termux.jpg](https://user-images.githubusercontent.com/105335528/167863587-5529dfeb-8681-4265-9900-c085f216ca94.jpg)


download the version that was on the termux page, it already left me until this part but from there it doesn't happen

**Comment by KasRoudra** [comment]
@AlverNL117 Turn on hotspot and try again
