### ISSUE TITLE
Version 1.7

### ISSUE THREAD

**Issue by axelbl54** [KasRoudra/PyPhisher#56]
It give me the Error:  " zsh: segmentation fault python3 pyphisher.py

**Comment by KasRoudra** [comment]
@axelbl54 Delete old one and reclone again. Let me know if problem persists

**Comment by Darkeyes-web** [comment]
i had the same issue and it worked after deleting the old 1.6 from my system 
first try to search after the pyphisher.py file and delete it folder.
**find / -name '*pyphisher*'**
go to the folder and delete with **rm -R <path to folder where pyphisher.py is located>**
if you find a file go there and delete its folder and clone it again with git clone <url to the 1.7 version>
