### ISSUE TITLE
Can you also create a tool for email spoofing? 

### ISSUE THREAD

**Issue by sanjanamalik1** [KasRoudra/PyPhisher#59]
It would be helpful because I have tried lot of tools and they do not work for email spoofing. Kindly please create one.

**Comment by KasRoudra** [comment]
@sanjanamalik1 Can you give links of that tools?

**Comment by sanjanamalik1** [comment]
For example - The SET tool kit has the feature to send e-mails but it does not work.

**Comment by KasRoudra** [comment]
@sanjanamalik1 I checked the tool and found it is too complex. I can't pay time for this in upcoming months. However, I have plan to create a email spoofing script in near future. Stay tuned!
