### ISSUE TITLE
no internet, please help

### ISSUE THREAD

**Issue by Lilpablo999** [KasRoudra/PyPhisher#66]
python3 pyphisher.py                                                        130 ⨯

[+] Please wait!
                                                                                      
[!] No internet!                                                                      
[!] No internet!                                                                      
                                 here is the error

**Comment by KasRoudra** [comment]
@Lilpablo999 The internet is checked by pure python. This means your internet speed is slow or unavailable. Try restarting your device

**Comment by Lilpablo999** [comment]
i just restart my device and still the samething

**Comment by Lilpablo999** [comment]
and other tools are working

**Comment by KasRoudra** [comment]
@Lilpablo999 Are you using any vpn? If not, try using one. And let me know your operating system and python version

**Comment by Lilpablo999** [comment]
i'm using express vpn running on kali linux and i have  Python 3.9.8

**Comment by KasRoudra** [comment]
@Lilpablo999 Does the problem occur with vpn on and off both?

**Comment by Lilpablo999** [comment]
No did you mean i should the vpn?

**Comment by Lilpablo999** [comment]
Ohh noo vpn is stable and working perfectly have restart my device many times still the same error

**Comment by KasRoudra** [comment]
@Lilpablo999 I am not saying your vpn is unstable. I assume your vpn is preventing pyphisher from accessing `8.8.8.8`

**Comment by Lilpablo999** [comment]
oh got it but what did you think i should do please?

**Comment by KasRoudra** [comment]
@Lilpablo999 Firstly, you should check if PyPhisher works correctly when vpn is off

**Comment by Lilpablo999** [comment]
yes now is working perfectly after i off vpn Thanks soo much
did i need to off vpn anytime i want to use it?

**Comment by KasRoudra** [comment]
@Lilpablo999 It seems that although your vpn is stable but it still blocks PyPhisher from accessing internet. So it is recommended to use PyPhisher turning off vpn each time

**Comment by Lilpablo999** [comment]
okay bro understood,Thanks for amazing working.

**Comment by KasRoudra** [comment]
@Lilpablo999 You're welcome. If you liked it, give a star, share it with others. It will inspire me to improve PyPhisher. And I think you can close this issue now
