### ISSUE TITLE
Custom link not working?

### ISSUE THREAD

**Issue by 565914** [KasRoudra/PyPhisher#71]
Pls help me how to fix custom link 😭😭😭😭😭😭 I'm real crying right now

**Comment by KasRoudra** [comment]
@565914 Give your screenshot, I've given mine

**Comment by 565914** [comment]
![Screenshot_2022-06-08-19-16-01-046_com.termux.jpg](https://user-images.githubusercontent.com/105534868/172610358-1b4b3430-7d6e-43a3-8125-e135213970c8.jpg)

**Comment by KasRoudra** [comment]
@565914 Manually visit https://is.gd and check the error

**Comment by 565914** [comment]
This site can't be reached

**Comment by 565914** [comment]
> @565914 Manually visit https://is.gd and check the error

Pls help me

**Comment by KasRoudra** [comment]
@565914 Are you under some vpn? Your network is blocking is.gd

**Comment by 565914** [comment]
I'm not using vpn

**Comment by 565914** [comment]
Pls help

**Comment by KasRoudra** [comment]
@565914 If you try from another device, does this still occur?

**Comment by 565914** [comment]
Yes

**Comment by 565914** [comment]
Can you help me to install termux Packages properly

**Comment by 565914** [comment]
Pls help me 😭😭😭😭😭😭

**Comment by KasRoudra** [comment]
@565914 What are the termux packages?
