### ISSUE TITLE
Tunnels not working 

### ISSUE THREAD

**Issue by NightbotLeL** [KasRoudra/PyPhisher#72]
How do i activate Tunnels?

**Comment by NightbotLeL** [comment]
![Screenshot_20220613-125758_Termux](https://user-images.githubusercontent.com/64130599/173339395-6cf7b1c3-99f3-4729-b956-c923bfa13a9e.jpg)

**Comment by KasRoudra** [comment]
@NightbotLeL Turn off wifi and turn on hotspot. Then restart pyphisher

**Comment by NightbotLeL** [comment]
Thanks it work
