### ISSUE TITLE
another page update 

### ISSUE THREAD

**Issue by oaosdpo** [KasRoudra/PyPhisher#74]
can you update page so it has the blue box when you click on it it surrounds the login box and email and phone are on the top of the line when you click out of the box it goes back to grey and email and phone is in the login field again. will you be able to do this?

**Comment by KasRoudra** [comment]
@oaosdpo I can't understand. Divide your requirements into multiple sentences

**Comment by oaosdpo** [comment]
imgur.com/a/G7DXgev

**Comment by oaosdpo** [comment]
add this the blue box when you click it an animation plays so it turns blue when you click out of it that turns grey

**Comment by oaosdpo** [comment]
it works with this code https://github.com/jakedmurphy1/GooglePhishing

**Comment by oaosdpo** [comment]
the only thing it is missing is the progress bar script

**Comment by KasRoudra** [comment]
@oaosdpo This page also has problems. During onblur, it hides the email. Then it unnecessarily appends `clients.com` into email. And in the password field, there is also a weird icon. But I also couldn't find a `progress bar` in that page
