### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by DLCShredderX** [KasRoudra/PyPhisher#77]
Ok so this is technically not a issue but can u make the redirection to the site home page instead of password reset?
Hope u will take this in to consideration on next update

**Comment by DLCShredderX** [comment]
How do i exactly do it bro?

**Comment by KasRoudra** [comment]
@DLCShredderX Suppose, you want to do this for facebook. Now go to `~/.websites/facebook`. In this directory you will find a file named `login.php`. This file contains redirection url. Edit that line according to your need and save that. You are done!
