### ISSUE TITLE
Php

### ISSUE THREAD

**Issue by Chomikmarkus** [KasRoudra/PyPhisher#8]
Cannot get it to run! getting previous php session...

![Screenshot_20211015-093319](https://user-images.githubusercontent.com/92059377/137442663-13743940-99c6-4840-98ba-36fa0c518b01.png)

**Comment by Chomikmarkus** [comment]
Works perfectly on cloudfare!! Ngrok links not! (Tunnel ca12-82-221-141-5.ngrok.io not found

ERR_NGROK_3200)

Tool itself is wonderful! Would be cool functions like in adv  OTP, template creator(pages,letters)

Keep it up ;)

**Comment by Chomikmarkus** [comment]
Listen, question where i could contact you beside here?

**Comment by KasRoudra** [comment]
@Chomikmarkus A web developer may help you in this purpose. Currently I do not have enough knowledge in web developing. The website templates in PyPhisher are collected, I didn't create them. So, I can't help you.
