### ISSUE TITLE
Site wont load

### ISSUE THREAD

**Issue by DLCShredderX** [KasRoudra/PyPhisher#80]
The website is not completely loading, can u pls say is it a problem from my side or the program side?
but it does grab the ip but the website wont load or show the login page, why?
![image](https://user-images.githubusercontent.com/96828518/176866698-b53fd08b-d5f2-4f3e-bd73-3ea3d9113341.png)

**Comment by KasRoudra** [comment]
@DLCShredderX Does it happen for every template you tried? If specific, which template?

**Comment by DLCShredderX** [comment]
It happens for every template........

**Comment by KasRoudra** [comment]
@DLCShredderX Create a ngrok account and then use ngrok urls. Instructions #1
