### ISSUE TITLE
Templates or some shi

### ISSUE THREAD

**Issue by rrryyybb9** [KasRoudra/PyPhisher#81]
![IMG_20220704_154124](https://user-images.githubusercontent.com/108678363/177166922-181a6130-8d55-4193-8454-21f23e099739.jpg) what do i do here help

**Comment by KasRoudra** [comment]
@rrryyybb9 Delete old one and reclone
```
rm -rf PyPhisher pyphisher && git clone https://github.com/KasRoudra/PyPhisher && cd PyPhisher && python pyphisher.py
```
