### ISSUE TITLE
Site Blocked Issue

### ISSUE THREAD

**Issue by Comrad30** [KasRoudra/PyPhisher#85]
Suspected Phishing Site!
This link has been flagged as phishing. We have blocked it for your safety.

Showing This Every time Please Fixed This Problem. 

I am trying all Browser,instant blocked.

So I figured Out Cloudfare Block The link Only. I am Using Custom Link (Url Snorter) Its not Working on Ngrock its Automatic Shorten Cloudfare link How i can Use Custom Url Changer Ngrock link.
please Remove Cloudfare server.

**Comment by KasRoudra** [comment]
@Comrad30 You can set url shortener to ngrok by running this `python3 pyphisher.py -t Ngrok`
