### ISSUE TITLE
OTP in new version (1.8) faulty

### ISSUE THREAD

**Issue by petrovichalex** [KasRoudra/PyPhisher#87]
After clicking on "i want otp page" and following all steps and getting to the 2 step authentication which is the otp, i shows me what i think is an Indian  number "+91" instead of showing the number i put. what is the problem??

**Comment by KasRoudra** [comment]
@petrovichalex This is because currently the country code is not dynamic but hardcoded. However, I will fix it in next update. From which template(s) you get this issue?

**Comment by petrovichalex** [comment]
Understood! Please do make sure to fix it, because i have taught quite a number of people your phishing software and i have shared it around with many people. I personally LOVE IT! 

I get this issue with (paypal, gmail, instagram, facebook and almost all 20 templates that supports OTP. 

I have never seen any repository on github that has over 77 functional templates, and not only that but has cloudfare and ngrok working perfectly and not breaking or saying 404 error or anything like that. I also saw you added PayPal, i'd want to plead with you to consider adding Cashapp and Zelle or Venmo in your next update, if you do that, you have taken over the game, i can assure you😉. And i want to thank you once again for coding this wonderful piece, it's amazing!

**Comment by petrovichalex** [comment]
I wanted to also ask, when is this next update coming out?

**Comment by KasRoudra** [comment]
@petrovichalex Thanks! I usually publish update after one month of current update. If there are major bugs, the update may arrive sooner. As you've mentioned, looks like I have to update 20 templates which requires a lot of time. And if I add more template the update is going to delayed more. However, I plan the next update to be arrived within two weeks with 20 templates fix. Newer templates may arrive in version 2.

**Comment by petrovichalex** [comment]
Oh wow, that's great to know! We can't wait for the new update to be out!🤗 So will you add Cashapp as one of the new templates in version 2?

Hey man, i think we should exchange contacts, cause there are some other projects i'd like for you to look into for me. My telegram is https://t.me/Bryan18181.

**Comment by KasRoudra** [comment]
@petrovichalex Yeap, if I will try. If the websites of cashapp/zelle aren't secure enough, I will be successful. But I don't use telegram. Propose your changes here

**Comment by petrovichalex** [comment]
That's totally fine! I believe, if PayPal isn't secure and you were successful in the template creation, it will be the same for Cashapp. I await the new versions🤗

**Comment by KasRoudra** [comment]
@petrovichalex Check the update. I've managed to add venmo

**Comment by petrovichalex** [comment]
@KasRoudra Wow, that is great! I will check it out right away

**Comment by petrovichalex** [comment]
@KasRoudra I just checked it, seems like just the cloudflare and loclX tunnelers are working except ngrok, that's probably why whenever i click on the link to open the site, it either shows me a 404 error or says something is wrong.

Secondly, thanks for setting up the OTP stuff, i guess you haven't done the routing/sending  of the OTP sms yet right? cause i put my US number and did not recieve code.

By the way, everything looks amazing!

**Comment by KasRoudra** [comment]
@petrovichalex Thanks! Ngrok requires ngrok authtoken to work. Still you will always get a warning page from ngrok each time you open a ngrok link. Paid accounts are free from this issue. Currently, I don't know that much to set up server and send otp. That feature may arrive in a future update

**Comment by ChillVibesMushroom** [comment]
> @petrovichalex Thanks! Ngrok requires ngrok authtoken to work. Still you will always get a warning page from ngrok each time you open a ngrok link. Paid accounts are free from this issue. Currently, I don't know that much to set up server and send otp. That feature may arrive in a future update. For now, you have to immediately log into real website with the credentials. This way, victim will receive the otp, which will be also captured by us after his input

what do you recommmend I do if Im red teaming right now with my co worker  I need to get past the alert page any thoughts? I was thinking about using this and linode and running it that way.

**Comment by ChillVibesMushroom** [comment]
can I edit the coding to make the server run on 80 please? where would I edit that in ill dissect the script but lmk because I have a tunneling service I can use even though it isnt that great tbh sometimes it doesnt capture traffic :(

**Comment by KasRoudra** [comment]
@ChillVibesMushroom Run `python3 pyphisher.py -p 80` to run in 80 port
