### ISSUE TITLE
How can I change the redirect website in the link

### ISSUE THREAD

**Issue by timkatta5** [KasRoudra/PyPhisher#88]
How do we change the redirected site once a user submits the form, and is redirected to a different site.
Is there an option or a location where we can change in the text where the login button leads you.

**Comment by KasRoudra** [comment]
@timkatta5 Sure. You need to go `$HOME/.websites/your_template`. In this directory you will find a `login.php`. Edit the link in that file

**Comment by ChillVibesMushroom** [comment]
Thats not in my home directory
