### ISSUE TITLE
Kali linux PyPhisher

### ISSUE THREAD

**Issue by Rizzlxh** [KasRoudra/PyPhisher#90]
hey ive installed correctly and when i run python3 pyphisher.py all i get is a orange plus sign that says please wait and nothing changes , how do i fix this  ?
![2022-07-26 (3)](https://user-images.githubusercontent.com/109990664/181048223-3e1ba9da-b686-450a-8c9c-b73da0a4d6e0.png)

**Comment by KasRoudra** [comment]
@Rizzlxh Try using version 1.7 and let me know if problem persists.
`git checkout 1.7`
`python3 pyphisher.py --noupdate`
Latest version uses some new modules which aren't supported in some device

**Comment by Rizzlxh** [comment]
now im stuck on this instead lol 
![2022-07-26 (6)](https://user-images.githubusercontent.com/109990664/181054946-90a81ae6-0ac3-44b9-84da-2fbc526feb7c.png)

**Comment by KasRoudra** [comment]
@Rizzlxh Maybe a slow internet connect. For some reason my code can't access your internet. Try running other python code which uses internet

**Comment by WhiskeyTangoFoxtrot08** [comment]
> @Rizzlxh Maybe a slow internet connect. For some reason my code can't access your internet. Try running other python code which uses internet

i have the same error........what other python you are talking about bud?

**Comment by KasRoudra** [comment]
@Rizzlxh Can you run this code https://github.com/thewhiteh4t/seeker ?
