### ISSUE TITLE
no more try.cloudfare.com URL

### ISSUE THREAD

**Issue by Alaponuke** [KasRoudra/PyPhisher#91]
Hello:
I am learning ethical hacking, and I am learning how to use pyphiser.
I did three or 4 test and worked perfect (thank for this great tool) but after those test the tool can not create any try.cloudfare.com URL only Ngrok url which are not goof to use directly due to the warning message. 
I was trying to create a user awareness campaign of email phishing for the company that I worked to show GM, that we need to invest in training.
My question is: is there any limitation or something that I need to do to continue creating cloudfare URL? in pyphising? do I need to configure something ?
sorry for this basic questions but as I said I am just learning.

Kind regards,

**Comment by KasRoudra** [comment]
@Alaponuke Cloudflared is a third party service. That is maintained by cloudflare authority. If you don't get cloudflare link, that means the server is busy. You should try again later in that case. And in next update I'll be adding a new service for link. Thanks!

**Comment by Alaponuke** [comment]
ok, fantastic, thanks soooooo much for your fast reply, I am newbie on this kind of things I Just dot really know how all is working.
Again, thanks sooo much for this great tool that helped me to show company GM how important is investing in user awareness.

Kind regards,

**Comment by KasRoudra** [comment]
@Alaponuke If you don't have any more query, you may close this issue
