### ISSUE TITLE
'cloudflared failed to start' and 'tunneling failed to start'.

### ISSUE THREAD

**Issue by njabcde** [KasRoudra/PyPhisher#92]
Please fix this.

**Comment by KasRoudra** [comment]
@njabcde It's not an error of my code. You have to troubleshoot your device for this. Run 

```
cd $HOME/.cffolder && ls &&  ./cloudflared tunnel -url 127.0.0.1:8080
```
and give screenshot here

**Comment by KhSh2** [comment]
Hi, I got the same fist error and I got this while running the command you sent : '-bash: ./cloudflared: No such file or directory'.
But, if I run 'cloud flared --version', I get : 'cloudflared version 2022.7.1 (built 2022-07-06-1226 UTC)'.

**Comment by KasRoudra** [comment]
@KhSh2 Are you using mac?

**Comment by KhSh2** [comment]
@KasRoudra yes

**Comment by techstartupexplorer** [comment]
at first its working tried different services then suddenly its not working did no changes
                                                                                                                                                                                                              
[•] Initializing tunnelers at same address.....                                                                                                                                                                                              
                                                                                                                                                                                                                                             
[!] Tunneling failed! Use your own tunneling service on port 8080!
