### ISSUE TITLE
Clouflared failed to start

### ISSUE THREAD

**Issue by KhSh2** [KasRoudra/PyPhisher#94]
Hi ! 

I got the error 'Cloudlared failed to start' multiple times while trying to run the program.

**Comment by KhSh2** [comment]
<img width="479" alt="Capture d’écran 2022-08-07 à 16 18 01" src="https://user-images.githubusercontent.com/86683150/183295219-f7c5288b-5f01-42e7-b99c-9fa0c5d703f1.png">

**Comment by KasRoudra** [comment]
@KhSh2 Run this to troubleshoot
`cd ~/.tunneler && ./cloudflared tunnel -url 127.0.0.1:8080`

**Comment by KhSh2** [comment]
@KasRoudra it's saying '-bash: ./cloudflared: No such file or directory'

**Comment by KasRoudra** [comment]
@KhSh2 Then run
`cd ~/.tunneler && cloudflared tunnel -url 127.0.0.1:8080 --logfile cf.log`
`cat cf.log`

**Comment by KhSh2** [comment]
@KasRoudra it just stopped from now several minutes. 

<img width="1431" alt="Capture d’écran 2022-08-07 à 17 24 32" src="https://user-images.githubusercontent.com/86683150/183298407-302a77a7-1f23-4feb-b356-7268d044485e.png">

**Comment by KhSh2** [comment]
@KasRoudra I'm currently running the first command but it stopped and it's not doing anything.
<img width="1431" alt="Capture d’écran 2022-08-07 à 17 24 32" src="https://user-images.githubusercontent.com/86683150/183298762-ec6cfd72-50b8-4a04-a4b6-6169e412b00f.png">

**Comment by KhSh2** [comment]
@KasRoudra it just stopped from now 20 minutes

**Comment by KasRoudra** [comment]
@KhSh2 Actually the mac support of my code is experimental because I can't test my code on mac. So you may need to troubleshoot more.
```
command -v brew && command -v ngrok && command -v cloudflared && command -v localxpose
```
Send screenshot

**Comment by KhSh2** [comment]
@KasRoudra It gave me this : 
<img width="193" alt="Capture d’écran 2022-08-07 à 17 46 18" src="https://user-images.githubusercontent.com/86683150/183299311-7da41bd6-d984-4728-adb9-443cd83a4a8d.png">

**Comment by KasRoudra** [comment]
@KhSh2 Localxpose seems to be missing. Install localxpose by `brew install localxpose`

**Comment by KhSh2** [comment]
@KasRoudra
<img width="499" alt="Capture d’écran 2022-08-07 à 17 55 53" src="https://user-images.githubusercontent.com/86683150/183299712-2fc73e2e-48fc-4231-956a-6a9dc40332f2.png">

**Comment by KasRoudra** [comment]
@KhSh2 Now, if you run PyPhisher, do you get any url?

**Comment by KhSh2** [comment]
@KasRoudra no, the same errors come

**Comment by KhSh2** [comment]
@KasRoudra I tried again this command 'cd ~/.tunneler && cloudflared tunnel -url 127.0.0.1:8080 --logfile cf.log' but it's still stopping and not doing anything after.

**Comment by KasRoudra** [comment]
@KhSh2 Unexpected behaviour. Install docker and run the docker image of PyPhisher

**Comment by KhSh2** [comment]
@KasRoudra I'm finishing to install Docker but I'm not understanding what does 'run the docker image of Pyphisher' means and where do I get it

**Comment by KasRoudra** [comment]
@KhSh2 Check [here](https://github.com/KasRoudra/PyPhisher#docker)
