### ISSUE TITLE
CUSTOM Link Url 

### ISSUE THREAD

**Issue by Comrad30** [KasRoudra/PyPhisher#95]
CUSTOM Link Url Not Opening In Messenger?
How to Fixed This?

**Comment by KasRoudra** [comment]
@Comrad30 Skip the part before "@". From latest update if messenger, "@" prefixed links are treated as email. Like if you have `https://abcd-bdcy-vysbbs@is.gd/gyijdh` then real url will be `https://is.gd/gyidjh`. Send this one
