### ISSUE TITLE
PyPhisher won't detect network, please help

### ISSUE THREAD

**Issue by RaduTheHacker** [KasRoudra/PyPhisher#97]
When starting the PyPhisher with python3 pyphisher.py command, it starts and then shows the error: 
"Please wait!"
"No internet!"

that when I clearly have internet and I tested google and speedtest, what am I doing wrong?

**Comment by KasRoudra** [comment]
@RaduTheHacker PyPhisher tests internet against google DNS. If you're under a proxy or using vpn you may need to turn of that
