### ISSUE TITLE
trycloudflare no longer working

### ISSUE THREAD

**Issue by techstartupexplorer** [KasRoudra/PyPhisher#98]
when you access the link generated by pyphisher -

error in all browsers:

Error 1033 Ray ID: 737a2193ff309d22 • 2022-08-08 17:56:52 UTC
Argo Tunnel error

\
===

[•] Initializing PHP server at localhost:8080....

[+] PHP Server has started successfully!

[•] Initializing tunnelers at same address.....

[√] Cloudflared has started successfully!

[+] Your urls are given below:

[•] URL 1 > 

pyphisher did run successfully generated 2 links from trycloudflare.com that doesn't work.

**Comment by KasRoudra** [comment]
@techstartupexplorer It's not an error of PyPhisher itself. Rather it is caused due to limitation of third party service [Cloudflared](https://github.com/cloudflare/cloudflared). Try using ngrok links or grab a loclx token

**Comment by techstartupexplorer** [comment]
ok cool... how to try ngrok link using pyphiser?

**Comment by KasRoudra** [comment]
@techstartupexplorer Follow this #1

**Comment by techstartupexplorer** [comment]
okay cool
