### ISSUE TITLE
Deceptive site ahead Attackers on 89e1-69-79-194-114.ngrok.io may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards)

### ISSUE THREAD

**Issue by techspotmich** [KasRoudra/PyPhisher#99]
good day i am new here and to pyphisher and i was wondering if there is any bypass to let google don't detect your phishing sites when i put the link in the url it says "Deceptive site ahead
Attackers on 89e1-69-79-194-114.ngrok.io may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards)"

**Comment by KasRoudra** [comment]
@techspotmich There is no way to bypass it. Secured browsers will always show warning against possible phishing domain. Try using cloudflared or use loclx (with account)

**Comment by techspotmich** [comment]
when i use those what will it do

**Comment by KasRoudra** [comment]
@techspotmich They are new and currently most browsers don't detect them as phishing site. So victim won't get warning

**Comment by techspotmich** [comment]
okay thank
